CREATE TABLE IF NOT EXISTS mabarchive.my_radtrack_reports (
    year smallint NOT NULL,
    project character varying(20) NOT NULL,
    type character varying(10) NOT NULL,
    reminder1 timestamp without time zone,
    reminder2 timestamp without time zone,
    replyreceived timestamp without time zone,
    senttoprogmanager timestamp without time zone,
    senttoprojleader timestamp without time zone,
    emailedtocustomer timestamp without time zone,
    signedcopytocustomer timestamp without time zone,
    repduedate timestamp without time zone,
    id integer GENERATED BY DEFAULT AS IDENTITY,
    reportagreeddate timestamp without time zone,
    CONSTRAINT pk_my_radtrack_reports PRIMARY KEY (id)
);

-- Foreign keys for mabarchive.my_radtrack_reports
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_my_radtrack_reports_g_tlkpproject_radtrackdata'
          AND conrelid = 'mabarchive.my_radtrack_reports'::regclass
    ) THEN
        ALTER TABLE mabarchive.my_radtrack_reports
            ADD CONSTRAINT fk_my_radtrack_reports_g_tlkpproject_radtrackdata FOREIGN KEY (project) REFERENCES mabarchive.g_tlkpproject_radtrackdata(parentproject);
    END IF;
END $$;
