CREATE TABLE IF NOT EXISTS mabarchive.my_tblanimalreq (
    year smallint NOT NULL,
    jobcode character varying(20) NOT NULL,
    animaltype character varying(50) NOT NULL,
    numberofdays double precision NOT NULL,
    numberofanimals double precision NOT NULL,
    ar_counter integer GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_my_tblanimalreq PRIMARY KEY (ar_counter)
);
