CREATE TABLE IF NOT EXISTS mabarchive.tbladditionalcosts (
    ac_identity integer GENERATED BY DEFAULT AS IDENTITY,
    project character varying(50),
    year integer DEFAULT 0,
    accountcat character varying(50) NOT NULL,
    description character varying(100) NOT NULL,
    itemcost double precision DEFAULT 0,
    costentered double precision DEFAULT 0 NOT NULL,
    freq character varying(5),
    CONSTRAINT pk_tbladditionalcosts PRIMARY KEY (ac_identity)
);

-- Foreign keys for mabarchive.tbladditionalcosts
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tbladditionalcosts_tblprojectyear'
          AND conrelid = 'mabarchive.tbladditionalcosts'::regclass
    ) THEN
        ALTER TABLE mabarchive.tbladditionalcosts
            ADD CONSTRAINT fk_tbladditionalcosts_tblprojectyear FOREIGN KEY (year, project) REFERENCES mabarchive.tblprojectyear(yearno, project);
    END IF;
END $$;
