CREATE TABLE IF NOT EXISTS mabarchive.tblanimalreq (
    ar_identity integer GENERATED BY DEFAULT AS IDENTITY,
    project character varying(50),
    year integer DEFAULT 0,
    animaltype character varying(50) NOT NULL,
    number_of_days double precision DEFAULT 0,
    number_of_animals double precision DEFAULT 0,
    dailyrate double precision DEFAULT 0,
    CONSTRAINT pk_tblanimalreq PRIMARY KEY (ar_identity)
);

-- Foreign keys for mabarchive.tblanimalreq
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_tblprojectyear'
          AND conrelid = 'mabarchive.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE mabarchive.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_tblprojectyear FOREIGN KEY (project, year) REFERENCES mabarchive.tblprojectyear(project, yearno);
    END IF;
END $$;
