CREATE TABLE IF NOT EXISTS mabarchive.tblcomments (
    commentno integer GENERATED BY DEFAULT AS IDENTITY,
    project character varying(20) NOT NULL,
    year smallint NOT NULL,
    dateentered timestamp without time zone,
    topic character varying(25) NOT NULL,
    comment character varying,
    madeby character varying(50),
    CONSTRAINT pk_tblcomments PRIMARY KEY (commentno)
);

-- Foreign keys for mabarchive.tblcomments
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblcomments_tlkpcommenttopics'
          AND conrelid = 'mabarchive.tblcomments'::regclass
    ) THEN
        ALTER TABLE mabarchive.tblcomments
            ADD CONSTRAINT fk_tblcomments_tlkpcommenttopics FOREIGN KEY (topic) REFERENCES mabarchive.tlkpcommenttopics(topic);
    END IF;
END $$;
