CREATE TABLE IF NOT EXISTS mabarchive.tbllogmilestone (
    project character varying(20),
    number character varying(10),
    description character varying(500),
    datedue timestamp without time zone,
    datecompleted timestamp without time zone,
    dateformreceived timestamp without time zone,
    undersdreview smallint,
    ontarget smallint,
    projectleadercomment character varying,
    capscomment character varying(250),
    idtype character(1),
    datechanged timestamp without time zone,
    changedby character varying(10),
    updatetype character(1),
    id integer GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_tbllogmilestone PRIMARY KEY (id)
);
