CREATE TABLE IF NOT EXISTS mabarchive.tblproject (
    project character varying(50) NOT NULL,
    plancat character varying(50),
    projecttitle character varying(100),
    programme character varying(50),
    projectworkgroup character varying(50),
    contractprice double precision,
    startdate timestamp without time zone,
    disease character varying(50),
    startfyear double precision DEFAULT 0,
    customer_name character varying(50),
    contract_number character varying(50),
    submittedbyfname character varying(50),
    submittedbylname character varying(50),
    date_of_submission timestamp without time zone,
    prepared_by character varying(50),
    inflation integer DEFAULT 0,
    financialyears integer,
    notes character varying(255),
    euroconvrate double precision,
    isdefraproject smallint,
    CONSTRAINT pk_tblproject PRIMARY KEY (project)
);
