CREATE TABLE IF NOT EXISTS mabarchive.tblpublication (
    uid integer GENERATED BY DEFAULT AS IDENTITY,
    identifier character varying(50) NOT NULL,
    type character varying(3) NOT NULL,
    program character varying(10) NOT NULL,
    subject character varying(500),
    leadauthor character varying(50),
    otherauthors character varying(255),
    targetdate timestamp without time zone,
    submitted timestamp without time zone,
    published boolean NOT NULL,
    comments text,
    CONSTRAINT pk_tblpublication PRIMARY KEY (uid)
);

-- Foreign keys for mabarchive.tblpublication
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblpublication_tlkppublicationtype'
          AND conrelid = 'mabarchive.tblpublication'::regclass
    ) THEN
        ALTER TABLE mabarchive.tblpublication
            ADD CONSTRAINT fk_tblpublication_tlkppublicationtype FOREIGN KEY (type) REFERENCES mabarchive.tlkppublicationtype(type);
    END IF;
END $$;
