CREATE TABLE IF NOT EXISTS mabarchive.tblreportgroup (
    groupid integer GENERATED BY DEFAULT AS IDENTITY,
    description character varying(50) NOT NULL,
    CONSTRAINT pk_tblreportgroup PRIMARY KEY (groupid)
);
