CREATE TABLE IF NOT EXISTS mabarchive.tblradtrackinvoice (
    invoicecounter integer GENERATED BY DEFAULT AS IDENTITY,
    project character varying(20),
    plannedamount double precision,
    dueamount double precision,
    duedate timestamp without time zone,
    actualamount double precision,
    dateinvoiced timestamp without time zone,
    contract character varying(10),
    datejobsheetraised timestamp without time zone,
    invoiceref character varying(50),
    invoicepaid smallint DEFAULT 0 NOT NULL,
    CONSTRAINT pk_tblradtrackinvoice PRIMARY KEY (invoicecounter)
);

-- Foreign keys for mabarchive.tblradtrackinvoice
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblradtrackinvoice_g_tlkpproject_radtrackdata'
          AND conrelid = 'mabarchive.tblradtrackinvoice'::regclass
    ) THEN
        ALTER TABLE mabarchive.tblradtrackinvoice
            ADD CONSTRAINT fk_tblradtrackinvoice_g_tlkpproject_radtrackdata FOREIGN KEY (project) REFERENCES mabarchive.g_tlkpproject_radtrackdata(parentproject);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblradtrackinvoice_tblradtrackcontract'
          AND conrelid = 'mabarchive.tblradtrackinvoice'::regclass
    ) THEN
        ALTER TABLE mabarchive.tblradtrackinvoice
            ADD CONSTRAINT fk_tblradtrackinvoice_tblradtrackcontract FOREIGN KEY (contract) REFERENCES mabarchive.tblradtrackcontract(contract);
    END IF;
END $$;
