CREATE TABLE IF NOT EXISTS mabarchive.tblstaffrequ (
    sr_identity integer GENERATED BY DEFAULT AS IDENTITY,
    project character varying(50),
    year integer DEFAULT 0,
    wggrade character varying(20) NOT NULL,
    name character varying(50),
    nohours double precision DEFAULT 0,
    nodays double precision DEFAULT 0,
    chargerate double precision DEFAULT 0,
    payrate double precision,
    npr double precision,
    ohr double precision,
    CONSTRAINT pk_tblstaffrequ PRIMARY KEY (sr_identity)
);

-- Foreign keys for mabarchive.tblstaffrequ
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblstaffrequ_tblprojectyear'
          AND conrelid = 'mabarchive.tblstaffrequ'::regclass
    ) THEN
        ALTER TABLE mabarchive.tblstaffrequ
            ADD CONSTRAINT fk_tblstaffrequ_tblprojectyear FOREIGN KEY (year, project) REFERENCES mabarchive.tblprojectyear(yearno, project);
    END IF;
END $$;
