CREATE TABLE IF NOT EXISTS mabarchive.temptbladditionalcosts (
    ac_identity integer GENERATED BY DEFAULT AS IDENTITY,
    project integer DEFAULT 0,
    year integer DEFAULT 0,
    accountcat character varying(50),
    description character varying(20),
    itemcost double precision DEFAULT 0,
    costentered double precision DEFAULT 0,
    freq character varying(5),
    CONSTRAINT pk_temptbladditionalcosts PRIMARY KEY (ac_identity)
);

-- Foreign keys for mabarchive.temptbladditionalcosts
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_temptbladditionalcosts_temptblprojectyear'
          AND conrelid = 'mabarchive.temptbladditionalcosts'::regclass
    ) THEN
        ALTER TABLE mabarchive.temptbladditionalcosts
            ADD CONSTRAINT fk_temptbladditionalcosts_temptblprojectyear FOREIGN KEY (project, year) REFERENCES mabarchive.temptblprojectyear(project, yearno);
    END IF;
END $$;
