CREATE TABLE IF NOT EXISTS mabarchive.temptblstaffrequ (
    sr_identity integer GENERATED BY DEFAULT AS IDENTITY,
    project integer DEFAULT 0,
    year integer DEFAULT 0,
    wggrade character varying(20),
    name character varying(50),
    nohours double precision DEFAULT 0,
    nodays double precision DEFAULT 0,
    chargerate double precision DEFAULT 0,
    CONSTRAINT pk_temptblstaffrequ PRIMARY KEY (sr_identity)
);

-- Foreign keys for mabarchive.temptblstaffrequ
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_temptblstaffrequ_temptblprojectyear'
          AND conrelid = 'mabarchive.temptblstaffrequ'::regclass
    ) THEN
        ALTER TABLE mabarchive.temptblstaffrequ
            ADD CONSTRAINT fk_temptblstaffrequ_temptblprojectyear FOREIGN KEY (project, year) REFERENCES mabarchive.temptblprojectyear(project, yearno);
    END IF;
END $$;
