CREATE TABLE IF NOT EXISTS mabarchive.temptblanimalreq (
    ar_identity integer GENERATED BY DEFAULT AS IDENTITY,
    project integer DEFAULT 0,
    year integer DEFAULT 0,
    animaltype character varying(50),
    number_of_days double precision DEFAULT 0,
    number_of_animals double precision DEFAULT 0,
    dailyrate double precision DEFAULT 0,
    CONSTRAINT pk_temptblanimalreq PRIMARY KEY (ar_identity)
);

-- Foreign keys for mabarchive.temptblanimalreq
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_temptblanimalreq_temptblprojectyear'
          AND conrelid = 'mabarchive.temptblanimalreq'::regclass
    ) THEN
        ALTER TABLE mabarchive.temptblanimalreq
            ADD CONSTRAINT fk_temptblanimalreq_temptblprojectyear FOREIGN KEY (year, project) REFERENCES mabarchive.temptblprojectyear(yearno, project);
    END IF;
END $$;
