<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Identity.Web" Version="4.6.0" />
	<PackageReference Include="Microsoft.Identity.Web.UI" Version="4.6.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	<PackageReference Include="AWSSDK.CloudWatchLogs" Version="4.0.15.3" />
    <PackageReference Include="Serilog.Sinks.AwsCloudWatch" Version="4.4.42" />
	<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
	<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
  </ItemGroup>

  <ItemGroup>    
    <ProjectReference Include="..\..\Apha.Common\Apha.Common.csproj" />    
    <ProjectReference Include="..\Apha.PACT.Application\Apha.PACT.Application.csproj" />
    <ProjectReference Include="..\Apha.PACT.DataAccess\Apha.PACT.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
