/*
 * TRANSFORMENGINE MIGRATION — ReportGroupDto.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 3 — Application Layer - DTOs + Service Interfaces + EntityMapper + Services (Steps 4-6)
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - New Application DTO mirroring Apha.PIMS.Core.Entities.ReportGroup
 *   - Groupid is GENERATED BY DEFAULT AS IDENTITY — integer PK on add
 *
 * PRESERVED:
 *   - All field names consistent with entity naming convention
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - none — fully automated.
 */

namespace Apha.PIMS.Application.Dtos
{
    // TRANSFORMENGINE: DTO maps to/from Apha.PIMS.Core.Entities.ReportGroup via EntityMapper
    public class ReportGroupDto
    {
        public int Groupid { get; set; }

        public string Description { get; set; } = null!;
    }
}
