CREATE OR REPLACE VIEW mabarchive.vcurrent_tlkpprojectradtrackdata AS
 SELECT my_tlkpprojectradtrackdata.year,
    my_tlkpprojectradtrackdata.project,
    my_tlkpprojectradtrackdata.bfbudget,
    my_tlkpprojectradtrackdata.pybudget,
    my_tlkpprojectradtrackdata.seedcorn,
    my_tlkpprojectradtrackdata.manhours,
    my_tlkpprojectradtrackdata.mandays,
    my_tlkpprojectradtrackdata.manyears,
    my_tlkpprojectradtrackdata.paycosts,
    my_tlkpprojectradtrackdata.nonpayohcosts,
    my_tlkpprojectradtrackdata.testcosts,
    my_tlkpprojectradtrackdata.animalcosts,
    my_tlkpprojectradtrackdata.nonanimalcosts,
    my_tlkpprojectradtrackdata.manhourschanged,
    my_tlkpprojectradtrackdata.paycostschanged,
    my_tlkpprojectradtrackdata.nonpayohcostschanged,
    my_tlkpprojectradtrackdata.testcostschanged,
    my_tlkpprojectradtrackdata.animalcostschanged,
    my_tlkpprojectradtrackdata.nonanimalcostschanged,
    my_tlkpprojectradtrackdata.adjustment,
    my_tlkpprojectradtrackdata.adjustmentcomment,
    my_tlkpprojectradtrackdata.locked,
    my_tlkpprojectradtrackdata.datecosted,
    my_tlkpprojectradtrackdata.costedby,
    my_tlkpprojectradtrackdata.actualexpenditure,
    my_tlkpprojectradtrackdata.actualmanyears,
    my_tlkpprojectradtrackdata.vla_budget
   FROM mabarchive.my_tlkpprojectradtrackdata
     JOIN mabarchive.vlatestmonthyear ON my_tlkpprojectradtrackdata.year = vlatestmonthyear.year;
