/*
 * TRANSFORMENGINE MIGRATION — ReportGroupReq.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 1 — Apha.Common - Shared Contracts (Step 1)
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - MS Access tblreportgroup VBA/DAO form binding -> .NET 10 ASP.NET Core request contract
 *   - Writable ControlSource fields from mabarchive.tblreportgroup surfaced as public properties
 *   - PK (groupid IDENTITY) excluded from Req; generated by DB on insert, supplied via route on update
 *
 * PRESERVED:
 *   - All column names and data types from mabarchive.tblreportgroup DDL
 *   - NOT NULL constraints reflected as non-nullable properties
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - TRANSFORMENGINE TODO: verify max length enforcement (50) with validation attributes if needed
 */

namespace Apha.Common.Contracts.PIMS
{
    // TRANSFORMENGINE: writable fields only — groupid (IDENTITY PK) excluded; DB-generated on insert
    public class ReportGroupReq
    {
        public string Description { get; set; } = null!;
    }
}
