-- View: mabarchive.vcurrent_projectinfo

CREATE OR REPLACE VIEW mabarchive.vcurrent_projectinfo AS
 SELECT my_tlkpproject.year,
    my_tlkpproject.parentproject,
    g_tlkpproject.projecttitle,
    g_tlkpproject.costbookno,
    g_tlkpproject.disease,
    g_tlkpproject.contract,
    g_tlkpproject.shorttitle,
    g_tlkpproject.projectstatus,
    my_tlkpproject.program,
    my_tlkpproject.customer,
    my_tlkpproject.manager,
    my_tlkpproject.transferincome,
    my_tlkpproject.custincome,
    my_tlkpproject.wip_eoy,
    my_tlkpproject.wip_limit,
    my_tlkpproject.wip_current,
    my_tlkpproject.datecreated,
    my_tlkpproject.feccost,
    my_tlkpproject.profit,
    my_tlkpproject.budget_cvl,
    my_tlkpproject.caseworksub,
    my_tlkpproject.pvsincome,
    my_tlkpproject.plancaseworkdebit,
    my_tlkpproject.source,
    my_tlkpprojectradtrackdata.bfbudget,
    my_tlkpprojectradtrackdata.pybudget,
    my_tlkpprojectradtrackdata.seedcorn,
    my_tlkpprojectradtrackdata.manhours,
    my_tlkpprojectradtrackdata.mandays,
    my_tlkpprojectradtrackdata.manyears,
    my_tlkpprojectradtrackdata.paycosts,
    my_tlkpprojectradtrackdata.nonpayohcosts,
    my_tlkpprojectradtrackdata.testcosts,
    my_tlkpprojectradtrackdata.animalcosts,
    my_tlkpprojectradtrackdata.nonanimalcosts,
    my_tlkpprojectradtrackdata.manhourschanged,
    my_tlkpprojectradtrackdata.paycostschanged,
    my_tlkpprojectradtrackdata.nonpayohcostschanged,
    my_tlkpprojectradtrackdata.testcostschanged,
    my_tlkpprojectradtrackdata.animalcostschanged,
    my_tlkpprojectradtrackdata.nonanimalcostschanged,
    my_tlkpprojectradtrackdata.adjustment,
    my_tlkpprojectradtrackdata.adjustmentcomment,
    my_tlkpprojectradtrackdata.locked,
    my_tlkpprojectradtrackdata.datecosted,
    my_tlkpprojectradtrackdata.costedby,
    my_tlkpprojectradtrackdata.actualexpenditure,
    my_tlkpprojectradtrackdata.actualmanyears,
    my_tlkpprojectradtrackdata.vla_budget,
    vg_tlkpprojectincome.totalprojectvalue,
    my_tlkpproject.projectgroup
   FROM ((((mabarchive.my_tlkpproject
     JOIN mabarchive.vlatestmonthyear ON ((my_tlkpproject.year = vlatestmonthyear.year)))
     JOIN mabarchive.g_tlkpproject ON (((my_tlkpproject.parentproject)::text = (g_tlkpproject.parentproject)::text)))
     JOIN mabarchive.vg_tlkpprojectincome ON (((g_tlkpproject.parentproject)::text = (vg_tlkpprojectincome.project)::text)))
     LEFT JOIN mabarchive.my_tlkpprojectradtrackdata ON (((my_tlkpproject.year = my_tlkpprojectradtrackdata.year) AND ((my_tlkpproject.parentproject)::text = (my_tlkpprojectradtrackdata.project)::text))));
