-- Table: fps.performance_log

CREATE TABLE fps.performance_log (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	log_type character varying(20) NOT NULL,
	start_time_utc timestamp without time zone NOT NULL,
	end_time_utc timestamp without time zone NOT NULL,
	duration_ms bigint NOT NULL,
	command_kind character varying(20),
	command_id character varying(50),
	command_text text,
	parameters text,
	api_name character varying(50),
	http_method character varying(10),
	status_code character varying(10),
	outcome character varying(100),
	url text,
	correlation_id character varying(100),
	created_at timestamp without time zone DEFAULT (now() at time zone 'utc') NOT NULL,
	CONSTRAINT pk_performance_log PRIMARY KEY (id)
);

CREATE INDEX ix_performance_log_start_time_utc ON fps.performance_log (start_time_utc);
CREATE INDEX ix_performance_log_log_type ON fps.performance_log (log_type);
CREATE INDEX ix_performance_log_duration_ms ON fps.performance_log (duration_ms);
