CREATE TABLE IF NOT EXISTS fps.additionalcosts_log (
    sequenceno integer GENERATED BY DEFAULT AS IDENTITY,
    jobcode character varying(20) NOT NULL,
    account character varying(50) NOT NULL,
    description character varying(20) NOT NULL,
    itemcost money NOT NULL,
    freq character varying(5),
    supplier character varying(50),
    date_time timestamp without time zone,
    user_id character varying(255),
    insert_delete character(2),
    fpsyear integer NOT NULL,
    CONSTRAINT pk_additionalcosts_log PRIMARY KEY (sequenceno, fpsyear)
)
PARTITION BY LIST (fpsyear);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_default PARTITION OF fps.additionalcosts_log
    DEFAULT;

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2016 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2016);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2017 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2017);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2018 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2018);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2019 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2019);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2020 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2020);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2021 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2021);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2022 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2022);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2023 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2023);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2024 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2024);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2025 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2025);

CREATE TABLE IF NOT EXISTS fps.additionalcosts_log_y2026 PARTITION OF fps.additionalcosts_log
    FOR VALUES IN (2026);

-- Foreign keys for fps.additionalcosts_log
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_additionalcosts_log_fpsyear'
          AND conrelid = 'fps.additionalcosts_log'::regclass
    ) THEN
        ALTER TABLE fps.additionalcosts_log
            ADD CONSTRAINT fk_additionalcosts_log_fpsyear FOREIGN KEY (fpsyear) REFERENCES fps.tblyearmaster(fpsyear);
    END IF;
END $$;
