CREATE TABLE IF NOT EXISTS fps.animalreq_log (
    sequenceno integer GENERATED BY DEFAULT AS IDENTITY,
    jobcode character varying(20) NOT NULL,
    animaltype character varying(50) NOT NULL,
    numberofdays double precision NOT NULL,
    numberofanimals double precision NOT NULL,
    date_time timestamp without time zone,
    user_id character varying(255),
    insert_delete character(2),
    fpsyear integer NOT NULL,
    CONSTRAINT pk_animalreq_log PRIMARY KEY (sequenceno, fpsyear)
)
PARTITION BY LIST (fpsyear);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_default PARTITION OF fps.animalreq_log
    DEFAULT;

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2016 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2016);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2017 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2017);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2018 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2018);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2019 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2019);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2020 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2020);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2021 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2021);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2022 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2022);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2023 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2023);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2024 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2024);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2025 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2025);

CREATE TABLE IF NOT EXISTS fps.animalreq_log_y2026 PARTITION OF fps.animalreq_log
    FOR VALUES IN (2026);

-- Foreign keys for fps.animalreq_log
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_animalreq_log_fpsyear'
          AND conrelid = 'fps.animalreq_log'::regclass
    ) THEN
        ALTER TABLE fps.animalreq_log
            ADD CONSTRAINT fk_animalreq_log_fpsyear FOREIGN KEY (fpsyear) REFERENCES fps.tblyearmaster(fpsyear);
    END IF;
END $$;
