CREATE TABLE IF NOT EXISTS fps.mt_log (
    sequenceno integer GENERATED BY DEFAULT AS IDENTITY,
    pactstaffid character varying(50) NOT NULL,
    timecode character varying(50) NOT NULL,
    month double precision NOT NULL,
    parentproject character varying(20) NOT NULL,
    workgroup character varying(50),
    hours double precision,
    date_time timestamp without time zone,
    user_id character varying(255),
    insert_delete character(2),
    fpsyear integer NOT NULL,
    CONSTRAINT pk_mt_log PRIMARY KEY (sequenceno, fpsyear)
)
PARTITION BY LIST (fpsyear);

CREATE TABLE IF NOT EXISTS fps.mt_log_default PARTITION OF fps.mt_log
    DEFAULT;

CREATE TABLE IF NOT EXISTS fps.mt_log_y2016 PARTITION OF fps.mt_log
    FOR VALUES IN (2016);

CREATE TABLE IF NOT EXISTS fps.mt_log_y2017 PARTITION OF fps.mt_log
    FOR VALUES IN (2017);

CREATE TABLE IF NOT EXISTS fps.mt_log_y2018 PARTITION OF fps.mt_log
    FOR VALUES IN (2018);

CREATE TABLE IF NOT EXISTS fps.mt_log_y2019 PARTITION OF fps.mt_log
    FOR VALUES IN (2019);

CREATE TABLE IF NOT EXISTS fps.mt_log_y2020 PARTITION OF fps.mt_log
    FOR VALUES IN (2020);

CREATE TABLE IF NOT EXISTS fps.mt_log_y2021 PARTITION OF fps.mt_log
    FOR VALUES IN (2021);

CREATE TABLE IF NOT EXISTS fps.mt_log_y2022 PARTITION OF fps.mt_log
    FOR VALUES IN (2022);

CREATE TABLE IF NOT EXISTS fps.mt_log_y2023 PARTITION OF fps.mt_log
    FOR VALUES IN (2023);

CREATE TABLE IF NOT EXISTS fps.mt_log_y2024 PARTITION OF fps.mt_log
    FOR VALUES IN (2024);

CREATE TABLE IF NOT EXISTS fps.mt_log_y2025 PARTITION OF fps.mt_log
    FOR VALUES IN (2025);

CREATE TABLE IF NOT EXISTS fps.mt_log_y2026 PARTITION OF fps.mt_log
    FOR VALUES IN (2026);

-- Foreign keys for fps.mt_log
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_mt_log_fpsyear'
          AND conrelid = 'fps.mt_log'::regclass
    ) THEN
        ALTER TABLE fps.mt_log
            ADD CONSTRAINT fk_mt_log_fpsyear FOREIGN KEY (fpsyear) REFERENCES fps.tblyearmaster(fpsyear);
    END IF;
END $$;
