CREATE TABLE IF NOT EXISTS fps.period_monthlyoutput (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    period integer NOT NULL,
    project character varying(20) NOT NULL,
    oracleprojectcode character varying(50),
    subaccountcode character varying(50),
    isdefraproject character varying(3) NOT NULL,
    opc character varying(50),
    occ double precision,
    month double precision NOT NULL,
    spc character varying(50) NOT NULL,
    workgroup character varying(50) NOT NULL,
    scc double precision,
    testcode character varying(20) NOT NULL,
    volume double precision,
    testprice money,
    totalcost money,
    CONSTRAINT pk_period_monthlyoutput_1 PRIMARY KEY (id)
);
COMMENT ON COLUMN fps.period_monthlyoutput.id IS 'Converted from IDENTITY(1,1) to SERIAL';
