CREATE TABLE IF NOT EXISTS fps.proj_subcontract (
    subcontcounter integer GENERATED BY DEFAULT AS IDENTITY,
    project character varying(20),
    testjob character varying(50),
    month double precision,
    amount money,
    workgroup character varying(50),
    acctcode character varying(30),
    supplier character varying(50),
    description character varying(255),
    suppliernumber integer,
    dailyrate money,
    animaldays integer,
    fpsyear integer NOT NULL,
    CONSTRAINT pk_proj_subcontract PRIMARY KEY (subcontcounter, fpsyear)
)
PARTITION BY LIST (fpsyear);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_default PARTITION OF fps.proj_subcontract
    DEFAULT;

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2016 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2016);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2017 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2017);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2018 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2018);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2019 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2019);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2020 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2020);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2021 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2021);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2022 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2022);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2023 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2023);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2024 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2024);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2025 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2025);

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_y2026 PARTITION OF fps.proj_subcontract
    FOR VALUES IN (2026);

-- Foreign keys for fps.proj_subcontract
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_fpsyear'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_fpsyear FOREIGN KEY (fpsyear) REFERENCES fps.tblyearmaster(fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_1'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_1 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2016(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_10'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_10 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2025(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_11'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_11 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2026(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_12'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_12 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_default(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_2'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_2 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2017(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_3'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_3 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2018(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_4'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_4 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2019(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_5'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_5 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2020(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_6'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_6 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2021(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_7'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_7 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2022(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_8'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_8 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2023(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_proj_subcontract_project_9'
          AND conrelid = 'fps.proj_subcontract'::regclass
    ) THEN
        ALTER TABLE fps.proj_subcontract
            ADD CONSTRAINT fk_proj_subcontract_project_9 FOREIGN KEY (project, fpsyear) REFERENCES fps.tlkpproject_y2024(parentproject, fpsyear);
    END IF;
END $$;
