CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    userid character varying(255),
    period smallint,
    datedone timestamp without time zone,
    fpsyear integer NOT NULL,
    CONSTRAINT pk_recreatesummaries_log PRIMARY KEY (id, fpsyear)
)
PARTITION BY LIST (fpsyear);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_default PARTITION OF fps.recreatesummaries_log
    DEFAULT;

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2016 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2016);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2017 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2017);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2018 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2018);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2019 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2019);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2020 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2020);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2021 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2021);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2022 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2022);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2023 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2023);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2024 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2024);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2025 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2025);

CREATE TABLE IF NOT EXISTS fps.recreatesummaries_log_y2026 PARTITION OF fps.recreatesummaries_log
    FOR VALUES IN (2026);

-- Foreign keys for fps.recreatesummaries_log
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_recreatesummaries_log_fpsyear'
          AND conrelid = 'fps.recreatesummaries_log'::regclass
    ) THEN
        ALTER TABLE fps.recreatesummaries_log
            ADD CONSTRAINT fk_recreatesummaries_log_fpsyear FOREIGN KEY (fpsyear) REFERENCES fps.tblyearmaster(fpsyear);
    END IF;
END $$;
