CREATE TABLE IF NOT EXISTS fps.tblanimalreq (
    jobcode character varying(20) NOT NULL,
    animaltype character varying(50) NOT NULL,
    numberofdays double precision DEFAULT 0 NOT NULL,
    numberofanimals double precision DEFAULT 0 NOT NULL,
    indcounter integer GENERATED BY DEFAULT AS IDENTITY,
    fpsyear integer NOT NULL,
    CONSTRAINT pk_tblanimalreq PRIMARY KEY (indcounter, fpsyear)
)
PARTITION BY LIST (fpsyear);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_default PARTITION OF fps.tblanimalreq
    DEFAULT;

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2016 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2016);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2017 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2017);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2018 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2018);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2019 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2019);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2020 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2020);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2021 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2021);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2022 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2022);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2023 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2023);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2024 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2024);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2025 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2025);

CREATE TABLE IF NOT EXISTS fps.tblanimalreq_y2026 PARTITION OF fps.tblanimalreq
    FOR VALUES IN (2026);

-- Foreign keys for fps.tblanimalreq
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_1'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_1 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2016(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_10'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_10 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2025(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_11'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_11 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2026(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_12'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_12 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_default(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_2'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_2 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2017(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_3'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_3 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2018(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_4'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_4 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2019(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_5'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_5 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2020(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_6'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_6 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2021(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_7'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_7 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2022(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_8'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_8 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2023(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_animaltype_9'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_animaltype_9 FOREIGN KEY (animaltype, fpsyear) REFERENCES fps.tblanimals_y2024(animaltype, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_fpsyear'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_fpsyear FOREIGN KEY (fpsyear) REFERENCES fps.tblyearmaster(fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_1'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_1 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2016(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_10'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_10 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2025(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_11'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_11 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2026(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_12'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_12 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_default(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_2'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_2 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2017(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_3'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_3 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2018(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_4'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_4 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2019(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_5'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_5 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2020(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_6'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_6 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2021(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_7'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_7 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2022(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_8'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_8 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2023(parentproject, fpsyear);
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tblanimalreq_jobcode_9'
          AND conrelid = 'fps.tblanimalreq'::regclass
    ) THEN
        ALTER TABLE fps.tblanimalreq
            ADD CONSTRAINT fk_tblanimalreq_jobcode_9 FOREIGN KEY (jobcode, fpsyear) REFERENCES fps.tlkpproject_y2024(parentproject, fpsyear);
    END IF;
END $$;
