CREATE TABLE IF NOT EXISTS fps.tlkpagency (
    agencyid integer GENERATED BY DEFAULT AS IDENTITY,
    agencyname character varying(18) NOT NULL,
    CONSTRAINT pk__tlkpagency__089551d8 PRIMARY KEY (agencyid),
    CONSTRAINT agencyname UNIQUE (agencyname)
);
