/*
 * TRANSFORMENGINE MIGRATION — AdditionalCostLogMap.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 4 — DataAccess Layer - DbContext + Map Files + Repository
 * Migrated : 2026-06-22
 *
 * CHANGED:
 *   - Phase 4 VERIFY: all 11 DDL columns confirmed mapped (sequenceno, jobcode, account, description,
 *     itemcost, freq, supplier, date_time, user_id, insert_delete, fpsyear)
 *   - Phase 4 VERIFY: composite PK (SequenceNo, FpsYear) confirmed — DDL CONSTRAINT pk_additionalcosts_log
 *   - Phase 4 VERIFY: ValueGeneratedOnAdd on SequenceNo confirmed — DDL: GENERATED BY DEFAULT AS IDENTITY
 *   - Phase 4 VERIFY: HasColumnType("money") on ItemCost confirmed — DDL: itemcost money NOT NULL
 *   - Phase 4 VERIFY: IsFixedLength on InsertDelete confirmed — DDL: insert_delete character(2)
 *   - Phase 4 VERIFY: indexes additionalcosts_log_ind_dt, additionalcosts_log_ind_jc, additionalcosts_log_pk_additionalcosts_log_idx confirmed
 *   - Added migration annotation header
 *
 * PRESERVED:
 *   - All HasColumnName() mappings (lowercase) verified against DDL
 *   - ToTable("additionalcosts_log", "fps") — lowercase preserved
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - TRANSFORMENGINE TODO: itemcost is PostgreSQL money type — verify EF Npgsql handles money → decimal
 *     correctly; HasColumnType("money") is set which should trigger Npgsql money mapping
 */
using Apha.FPS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Apha.FPS.DataAccess.Data
{
    public class AdditionalCostLogMap : IEntityTypeConfiguration<AdditionalCostLog>
    {
        public void Configure(EntityTypeBuilder<AdditionalCostLog> entity)
        {
            entity.HasKey(e => new { e.SequenceNo, e.FpsYear }).HasName("pk_additionalcosts_log");            

            entity.ToTable("additionalcosts_log", "fps");

            entity.HasIndex(e => e.DateTime, "additionalcosts_log_ind_dt");
            entity.HasIndex(e => e.JobCode, "additionalcosts_log_ind_jc");
            entity.HasIndex(e => e.SequenceNo, "additionalcosts_log_pk_additionalcosts_log_idx");

            entity.Property(e => e.SequenceNo)
                .ValueGeneratedOnAdd()
                .HasColumnName("sequenceno");

            entity.Property(e => e.FpsYear).HasColumnName("fpsyear");

            entity.Property(e => e.JobCode)
                .HasMaxLength(20)
                .HasColumnName("jobcode");

            entity.Property(e => e.Account)
                .HasMaxLength(50)
                .HasColumnName("account");

            entity.Property(e => e.Description)
                .HasMaxLength(20)
                .HasColumnName("description");

            entity.Property(e => e.ItemCost)
                .HasColumnType("money")
                .HasColumnName("itemcost");

            entity.Property(e => e.Freq)
                .HasMaxLength(5)
                .HasColumnName("freq");

            entity.Property(e => e.Supplier)
                .HasMaxLength(50)
                .HasColumnName("supplier");

            entity.Property(e => e.DateTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("date_time");

            entity.Property(e => e.InsertDelete)
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("insert_delete");

            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .HasColumnName("user_id");
        }
    }
}
