/*
 * TRANSFORMENGINE MIGRATION — AnimalRequestLogMap.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 4 — DataAccess Layer - DbContext + Map Files + Repository
 * Migrated : 2026-06-22
 *
 * CHANGED:
 *   - Phase 4 VERIFY: all 9 DDL columns confirmed mapped (sequenceno, jobcode, animaltype, numberofdays,
 *     numberofanimals, date_time, user_id, insert_delete, fpsyear)
 *   - Phase 4 VERIFY: composite PK (SequenceNo, FpsYear) confirmed correct per DDL CONSTRAINT pk_animalreq_log
 *   - Phase 4 VERIFY: ValueGeneratedOnAdd on SequenceNo confirmed — DDL: GENERATED BY DEFAULT AS IDENTITY
 *   - Phase 4 VERIFY: IsFixedLength on InsertDelete confirmed — DDL: insert_delete character(2)
 *   - Phase 4 VERIFY: indexes animalreq_log_ind_dt, animalreq_log_ind_jc confirmed
 *   - Added migration annotation header
 *
 * PRESERVED:
 *   - All HasColumnName() mappings (lowercase) verified against DDL
 *   - ToTable("animalreq_log", "fps") — lowercase preserved
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - TRANSFORMENGINE TODO: numberofdays and numberofanimals are double precision in DDL —
 *     verify EF maps PostgreSQL float8 → C# double correctly (no precision-loss risk for these fields)
 */
using Apha.FPS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Apha.FPS.DataAccess.Data
{
    public class AnimalRequestLogMap : IEntityTypeConfiguration<AnimalRequestLog>
    {


        public void Configure(EntityTypeBuilder<AnimalRequestLog> entity)
        {
            entity.HasKey(e => new { e.SequenceNo, e.FpsYear }).HasName("pk_animalreq_log");

            entity.ToTable("animalreq_log", "fps");

            entity.HasIndex(e => e.DateTime, "animalreq_log_ind_dt");
            entity.HasIndex(e => e.JobCode, "animalreq_log_ind_jc");

            entity.Property(e => e.SequenceNo)
                .ValueGeneratedOnAdd()
                .HasColumnName("sequenceno");
            entity.Property(e => e.FpsYear).HasColumnName("fpsyear");
            entity.Property(e => e.AnimalType)
                .HasMaxLength(50)
                .HasColumnName("animaltype");
            entity.Property(e => e.DateTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("date_time");
            entity.Property(e => e.InsertDelete)
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("insert_delete");
            entity.Property(e => e.JobCode)
                .HasMaxLength(20)
                .HasColumnName("jobcode");
            entity.Property(e => e.NumberOfAnimals).HasColumnName("numberofanimals");
            entity.Property(e => e.NumberOfDays).HasColumnName("numberofdays");
            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .HasColumnName("user_id");
        }
    }
}
