/*
 * TRANSFORMENGINE MIGRATION — StaffJobLogMap.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 4 — DataAccess Layer - DbContext + Map Files + Repository
 * Migrated : 2026-06-22
 *
 * CHANGED:
 *   - Phase 4 VERIFY: all 8 DDL columns confirmed mapped (sequenceno, staffid, jobcode, plannedhours,
 *     date_time, user_id, insert_delete, fpsyear)
 *   - Phase 4 VERIFY: composite PK (SequenceNo, FpsYear) confirmed correct per DDL CONSTRAINT pk_staffjob_log
 *   - Phase 4 VERIFY: ValueGeneratedOnAdd on SequenceNo confirmed — DDL: GENERATED BY DEFAULT AS IDENTITY
 *   - Phase 4 VERIFY: IsFixedLength on InsertDelete confirmed — DDL: insert_delete character(2)
 *   - Phase 4 VERIFY: indexes staffjob_log_ind_dt, staffjob_log_ind_jc, staffjob_log_pk_idx confirmed
 *   - Added migration annotation header
 *
 * PRESERVED:
 *   - All HasColumnName() mappings (lowercase) verified against DDL
 *   - ToTable("staffjob_log", "fps") — lowercase preserved
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - TRANSFORMENGINE TODO: plannedhours is double precision in DDL — verify EF maps double precision → double correctly
 */
using Apha.FPS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Apha.FPS.DataAccess.Data
{
    public class StaffJobLogMap : IEntityTypeConfiguration<StaffJobLog>
    {


        public void Configure(EntityTypeBuilder<StaffJobLog> entity)
        {
            entity.HasKey(e => new { e.SequenceNo, e.FpsYear }).HasName("pk_staffjob_log");

            entity.ToTable("staffjob_log", "fps");

            entity.HasIndex(e => e.DateTime, "staffjob_log_ind_dt");
            entity.HasIndex(e => e.JobCode, "staffjob_log_ind_jc");
            entity.HasIndex(e => e.SequenceNo, "staffjob_log_pk_idx");

            entity.Property(e => e.SequenceNo)
                .ValueGeneratedOnAdd()
                .HasColumnName("sequenceno");
            entity.Property(e => e.FpsYear).HasColumnName("fpsyear");
            entity.Property(e => e.DateTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("date_time");
            entity.Property(e => e.InsertDelete)
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("insert_delete");
            entity.Property(e => e.JobCode)
                .HasMaxLength(20)
                .HasColumnName("jobcode");
            entity.Property(e => e.PlannedHours).HasColumnName("plannedhours");
            entity.Property(e => e.StaffId)
                .HasMaxLength(50)
                .HasColumnName("staffid");
            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .HasColumnName("user_id");
        }
    }
}
