<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\PACT\IProfitCentreService.cs" />
    <Compile Remove="Services\PACT\ProfitCentreService.cs" />
  </ItemGroup>

  <ItemGroup>    
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\CostBook\" />
    <Folder Include="Dtos\PIMS\" />
  </ItemGroup>

</Project>
