USE [FPS2025]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblStatus](
    [Status] [varchar](50) NOT NULL
,    CONSTRAINT [PK___3__10] PRIMARY KEY NONCLUSTERED
    (
        Status
    )
) ON [PRIMARY]
GO
