-- View: fps.vprojectmonthfinal

CREATE OR REPLACE VIEW fps.vprojectmonthfinal AS
 SELECT project,
    monthno,
    periodname,
    cumflag,
    costprofile,
    subcontracts,
    animals,
    nonanimals,
    timecosts,
    transfercosts,
    totalcost,
    invoices,
    coiw,
    portsales,
    cumcost,
    cumprofile,
    sumofcostprofile,
    cuminvoices,
    cumcoiw,
    cumportsales,
    mstonedue,
    due__done,
    ontime,
    sumofmstonedue,
    sumofdue__done,
    sumofontime,
    cwdebit,
    cwcredit,
    cumcwdebit,
    cumcwcredit,
    totalhours,
    cumtotalhours,
    cumsubcontracts,
    x,
    cumtestcosts,
    paycosts,
    cumpaycosts,
    fpsyear
   FROM fps.projectmonthfinal
  WHERE ((project)::text IN ( SELECT vtlkpproject.parentproject
           FROM fps.vtlkpproject));
