/*
 * TRANSFORMENGINE MIGRATION — ReportGroupRepository.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 4 — DataAccess Layer - DbContext + Map Files + Repository
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - New EF Core LINQ-first repository implementing IReportGroupRepository
 *   - All read operations use AsNoTracking for performance
 *   - ExistsAsync uses AnyAsync guard pattern
 *   - DeleteAsync uses ExecuteDeleteAsync for set-based delete
 *   - AddAsync / UpdateAsync use EF change tracking + single SaveChangesAsync
 *
 * PRESERVED:
 *   - All method signatures defined in IReportGroupRepository (Phase 2)
 *   - mabarchive.tblreportgroup is the backing table (mapped via ReportGroupMap.cs)
 *   - Groupid is GENERATED BY DEFAULT AS IDENTITY — EF sets value on insert
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - TRANSFORMENGINE TODO: confirm ValueGeneratedOnAdd is set in ReportGroupMap.cs for Groupid
 */

using Apha.PIMS.Core.Entities;
using Apha.PIMS.Core.Interfaces;
using Apha.PIMS.DataAccess.Data;
using Microsoft.EntityFrameworkCore;

namespace Apha.PIMS.DataAccess.Repository
{
    // TRANSFORMENGINE: implements IReportGroupRepository — backs mabarchive.tblreportgroup (PostgreSQL)
    public class ReportGroupRepository : BaseRepository, IReportGroupRepository
    {
        private readonly PimsDbContext _dbContext;

        public ReportGroupRepository(PimsDbContext dbContext) : base(dbContext)
        {
            _dbContext = dbContext;
        }

        // TRANSFORMENGINE: AsNoTracking read — full list for Report Group dropdown / lookup
        public async Task<List<ReportGroup>> GetAllAsync()
        {
            return await _dbContext.ReportGroups
                .AsNoTracking()
                .OrderBy(g => g.Description)
                .ToListAsync();
        }

        // TRANSFORMENGINE: AsNoTracking single-row lookup by Groupid PK
        public async Task<ReportGroup?> GetByIdAsync(int groupid)
        {
            return await _dbContext.ReportGroups
                .AsNoTracking()
                .FirstOrDefaultAsync(g => g.Groupid == groupid);
        }

        // TRANSFORMENGINE: insert — EF Add + SaveChangesAsync; Groupid auto-generated
        public async Task<ReportGroup> AddAsync(ReportGroup entity)
        {
            _dbContext.ReportGroups.Add(entity);
            await _dbContext.SaveChangesAsync();
            return entity;
        }

        // TRANSFORMENGINE: update — EF Update + SaveChangesAsync
        public async Task<ReportGroup> UpdateAsync(ReportGroup entity)
        {
            _dbContext.ReportGroups.Update(entity);
            await _dbContext.SaveChangesAsync();
            return entity;
        }

        // TRANSFORMENGINE: set-based delete via ExecuteDeleteAsync
        public async Task DeleteAsync(int groupid)
        {
            await _dbContext.ReportGroups
                .Where(g => g.Groupid == groupid)
                .ExecuteDeleteAsync();
        }

        // TRANSFORMENGINE: AnyAsync guard — avoids full row load for existence check
        public async Task<bool> ExistsAsync(int groupid)
        {
            return await _dbContext.ReportGroups
                .AnyAsync(g => g.Groupid == groupid);
        }
    }
}
