// TRANSFORMENGINE: human_review — verify before running

/*
 * TRANSFORMENGINE MIGRATION — RadTrackInvoice.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 2 — Core Layer - Entities + Repository Interfaces + Pagination (Steps 2-3)
 * Migrated : 2026-06-12
 *
 * CHANGED:
 *   - New file: no prior C# entity existed for tblradtrackinvoice.
 *   - Entity columns derived from source/pgsql/mab_archive/Tables/tblradtrackinvoice.sql DDL.
 *   - PascalCase C# property names used; column-name mapping to lowercase PostgreSQL names
 *     deferred to EF IEntityTypeConfiguration (RadTrackInvoiceMap.cs, Phase 4).
 *   - InvoiceCounter is the IDENTITY primary key (integer GENERATED BY DEFAULT AS IDENTITY).
 *   - FK relationships (Project -> g_tlkpproject_radtrackdata, Contract -> tblradtrackcontract)
 *     noted; navigation properties intentionally omitted at Core layer.
 *   - RadTrackInvoiceTotals value object co-located here as a Core aggregate projection
 *     used by IRadTrackInvoiceRepository.GetTotalsAsync.
 *
 * PRESERVED:
 *   - All 11 column names from tblradtrackinvoice DDL retained verbatim (as PascalCase).
 *   - Field nullability follows DDL: invoicepaid is NOT NULL default 0; all others nullable.
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - TRANSFORMENGINE TODO: Confirm InvoicePaid should remain short (smallint) or be mapped
 *     to bool — tracked in checklist item. See RadTrackInvoiceReq/Res Phase 1 TODO.
 *   - TRANSFORMENGINE TODO: EF column mappings (HasColumnName, schema, table) are in Phase 4
 *     RadTrackInvoiceMap.cs — this entity carries no EF attributes by design (Core-clean rule).
 */

using System;

namespace Apha.PIMS.Core.Entities
{
    // TRANSFORMENGINE: Entity mapped to mabarchive.tblradtrackinvoice (PostgreSQL).
    // EF configuration (table name, schema, column names) applied via RadTrackInvoiceMap.cs in Phase 4.
    public partial class RadTrackInvoice
    {
        // TRANSFORMENGINE: invoicecounter — integer GENERATED BY DEFAULT AS IDENTITY; PK.
        public int InvoiceCounter { get; set; }

        // TRANSFORMENGINE: project — character varying(20); FK to mabarchive.g_tlkpproject_radtrackdata(parentproject). Nullable.
        public string? Project { get; set; }

        // TRANSFORMENGINE: plannedamount — double precision; nullable in DDL.
        public double? PlannedAmount { get; set; }

        // TRANSFORMENGINE: dueamount — double precision; nullable in DDL.
        public double? DueAmount { get; set; }

        // TRANSFORMENGINE: duedate — timestamp without time zone; nullable in DDL.
        public DateTime? DueDate { get; set; }

        // TRANSFORMENGINE: actualamount — double precision; nullable in DDL.
        public double? ActualAmount { get; set; }

        // TRANSFORMENGINE: dateinvoiced — timestamp without time zone; nullable in DDL.
        public DateTime? DateInvoiced { get; set; }

        // TRANSFORMENGINE: contract — character varying(10); FK to mabarchive.tblradtrackcontract(contract). Nullable.
        public string? Contract { get; set; }

        // TRANSFORMENGINE: datejobsheetraised — timestamp without time zone; nullable in DDL.
        public DateTime? DateJobsheetRaised { get; set; }

        // TRANSFORMENGINE: invoiceref — character varying(50); nullable in DDL.
        public string? InvoiceRef { get; set; }

        // TRANSFORMENGINE: invoicepaid — smallint NOT NULL DEFAULT 0; kept as short to mirror DDL type.
        // TRANSFORMENGINE TODO: Evaluate mapping to bool if the API surface prefers it (see checklist).
        public short InvoicePaid { get; set; }
    }

    // TRANSFORMENGINE: Lightweight value object for invoice totals aggregate — returned by
    // IRadTrackInvoiceRepository.GetTotalsAsync. Mirrors the totals row shown in the HTML prototype
    // (source/ui/pims/frmpimsinvoices.html): sum of PlannedAmount, DueAmount, ActualAmount.
    // Co-located with the entity to keep the Core layer self-contained; Application DTO (Phase 3)
    // will map from this type.
    public class RadTrackInvoiceTotals
    {
        // TRANSFORMENGINE: Sum of plannedamount across filtered result set.
        public double TotalPlannedAmount { get; set; }

        // TRANSFORMENGINE: Sum of dueamount across filtered result set.
        public double TotalDueAmount { get; set; }

        // TRANSFORMENGINE: Sum of actualamount across filtered result set.
        public double TotalActualAmount { get; set; }
    }
}
