/*
 * TRANSFORMENGINE MIGRATION — ReportGroup.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 2 — Core Layer - Entities + Repository Interfaces + Pagination
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - New Core entity derived from PostgreSQL DDL mabarchive.tblreportgroup
 *   - Groupid is GENERATED BY DEFAULT AS IDENTITY — auto-increment integer PK
 *
 * PRESERVED:
 *   - Column naming convention consistent with other entities in the project
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - TRANSFORMENGINE TODO: confirm EF Core ValueGeneratedOnAdd applied in ReportGroupMap.cs (Phase 4)
 */

namespace Apha.PIMS.Core.Entities
{
    // TRANSFORMENGINE: entity maps to mabarchive.tblreportgroup (PostgreSQL)
    public partial class ReportGroup
    {
        public int Groupid { get; set; }

        public string Description { get; set; } = null!;
    }
}
