using Apha.BatchJobs.Application.Jobs.ManualJobs.YearEnd.Execution;
using Apha.BatchJobs.Application.Jobs.ManualJobs.YearEnd.Steps;
using Apha.BatchJobs.Domain.Constants;
using Apha.BatchJobs.Domain.Interfaces;
using Apha.BatchJobs.Infrastructure.Data;
using Apha.BatchJobs.Infrastructure.YearEnd.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

namespace Apha.BatchJobs.UnitTests;

/// <summary>
/// PostgreSQL-backed integration tests for the <see cref="YearEndDataSetupRepository"/> methods added
/// for <c>MaterializeYearEndConfigurationStep</c>, plus one test that exercises the real step class
/// against a live-resolved <c>job_queue</c> row. Row-count assertions alone cannot catch a wrong column
/// mapping — this proves the actual staging-to-real column mapping is correct, that <c>updated_by</c>/
/// <c>updated_at</c>/<c>fmonth</c> are copied through from staging rather than regenerated by the Worker
/// (the 2026-09-07 staging simplification), and that the <c>fpsyear</c> fail-closed guard rejects a real
/// mismatched staged row rather than just a mocked one.
///
/// <c>[Collection("YearEndStaging")]</c>: since the 2026-09-07 staging simplification,
/// <c>fps.tblsettings_staging</c>/<c>fps.tlkpmonthhours_staging</c> are singletons — no <c>jobqueueid</c>
/// scoping any more. Two test classes writing to them concurrently (xUnit parallelizes different classes
/// by default) would corrupt each other's rows or trip each other's fail-closed <c>fpsyear</c> check.
/// This collection name is shared with <c>YearEndDataSetupRollbackValidationTests</c> specifically to
/// force both to run sequentially, never in parallel with each other.
/// </summary>
[Trait("Category", "Integration")]
[Collection("YearEndStaging")]
public sealed class YearEndDataSetupRepositoryMaterializationIntegrationTests : IAsyncLifetime
{
    private const string DefaultConnectionString = "Host=localhost;Port=5432;Database=batch_jobs_foundation_db;Username=postgres;Timeout=30";

    // Fake far-future year — avoids any collision with real fps.tblyearmaster data.
    private const int TargetFpsYear = 9091;

    // Fixed, non-"now" — proves updated_at is copied from staging, not regenerated at materialize time.
    // Utc kind, not Unspecified: EF Core's ExecuteSqlInterpolatedAsync binds a raw DateTime parameter as
    // `timestamptz` regardless of the actual target column type (confirmed live — the column really is
    // `timestamp without time zone`, per pg_attribute, but Npgsql still rejects Kind=Unspecified with
    // "only UTC is supported"). Session timezone on this connection is UTC (confirmed live via
    // SHOW TIMEZONE), so the implicit timestamptz -> timestamp cast on insert is a no-op shift.
    private static readonly DateTime StagedUpdatedAt = new(2026, 1, 15, 9, 30, 0, DateTimeKind.Utc);

    private readonly string _connectionString;
    private string? _skipReason;

    public YearEndDataSetupRepositoryMaterializationIntegrationTests()
    {
        _connectionString =
            Environment.GetEnvironmentVariable("ConnectionStrings__FPSConnectionString")
            ?? DefaultConnectionString;
    }

    public async Task InitializeAsync()
    {
        try
        {
            await using var context = CreateDbContext();
            if (!await context.Database.CanConnectAsync())
            {
                _skipReason = "Integration DB unavailable.";
            }
        }
        catch (Exception ex)
        {
            _skipReason = $"Integration DB unavailable: {ex.Message}";
        }
    }

    public Task DisposeAsync() => Task.CompletedTask;

    [SkippableFact]
    public async Task ResolveJobQueueByExecutionIdAsync_WhenJobIsNotYearEndDataSetup_ReturnsNull()
    {
        Skip.IfNot(CanRun(), _skipReason ?? "Integration DB unavailable.");

        var jobExecutionId = Guid.NewGuid();
        var jobQueueId = Guid.NewGuid();

        // Any other real job type — proves the fps.job_master join actually filters by jobname, not
        // just that the query compiles, so a JobExecutionId belonging to some other job (Bulk Rates,
        // RecreateSummaries, ...) never resolves as if it were a YearEnd-DataSetup request.
        await SeedJobQueueRowAsync(jobExecutionId, jobQueueId, BatchJobNames.RecreateSummary, targetFpsYear: null);

        try
        {
            var repository = CreateRepository();

            var resolved = await repository.ResolveJobQueueByExecutionIdAsync(jobExecutionId);

            Assert.Null(resolved);
        }
        finally
        {
            await CleanupJobQueueAsync(jobQueueId);
        }
    }

    [SkippableFact]
    public async Task MaterializeStagedConfiguration_RoundTripsEveryColumnExactly()
    {
        Skip.IfNot(CanRun(), _skipReason ?? "Integration DB unavailable.");

        var jobExecutionId = Guid.NewGuid();
        var jobQueueId = Guid.NewGuid();

        await SeedJobQueueRowAsync(jobExecutionId, jobQueueId, BatchJobNames.YearEndDataSetup, TargetFpsYear);

        // fps.tblsettings/fps.tlkpmonthhours both FK to fps.tblyearmaster(fpsyear) — confirmed live,
        // not visible from the EF mapping alone. In production this is always satisfied because
        // MaterializeYearEndConfigurationStep runs after CreatePlannedYearStep; this test must seed the
        // same precondition for its own fake target year.
        await SeedTargetYearMasterRowAsync(TargetFpsYear);

        const string settingId = "ws7-materialize-test";
        const string settingValue = "distinctive-setting-value";
        const string settingNotes = "distinctive-notes";
        const string stagedUpdatedBy = "integration-test-confirmer";
        const short year = 2031; // deliberately different from TargetFpsYear -- catches a year/fpsyear swap.
        const short month = 4;
        const short fmonth = 9;
        const decimal days = 21.5m;
        const decimal cvlHours = 123.4m;
        const decimal vidHours = 67.8m;

        try
        {
            await using (var context = CreateDbContext())
            {
                await context.Database.ExecuteSqlInterpolatedAsync($@"
                    INSERT INTO fps.tblsettings_staging (id, setting, notes, fpsyear, updated_by, updated_at)
                    VALUES ({settingId}, {settingValue}, {settingNotes}, {TargetFpsYear}, {stagedUpdatedBy}, {StagedUpdatedAt});");

                await context.Database.ExecuteSqlInterpolatedAsync($@"
                    INSERT INTO fps.tlkpmonthhours_staging (year, month, fmonth, days, cvlhours, vidhours, fpsyear)
                    VALUES ({year}, {month}, {fmonth}, {days}, {cvlHours}, {vidHours}, {TargetFpsYear});");
            }

            var repository = CreateRepository();

            var resolved = await repository.ResolveJobQueueByExecutionIdAsync(jobExecutionId);
            Assert.NotNull(resolved);
            Assert.Equal(jobQueueId, resolved!.Value.JobQueueId);
            Assert.Equal(TargetFpsYear, resolved.Value.TargetFpsYear);

            var settingsInserted = await repository.MaterializeStagedSettingsAsync(TargetFpsYear);
            Assert.Equal(1, settingsInserted);

            var monthHoursInserted = await repository.MaterializeStagedMonthHoursAsync(TargetFpsYear);
            Assert.Equal(1, monthHoursInserted);

            await using var assertContext = CreateDbContext();

            var setting = await assertContext.Database
                .SqlQuery<MaterializedSetting>($@"
                    SELECT setting AS ""Setting"", notes AS ""Notes"", updated_by AS ""UpdatedBy"", updated_at AS ""UpdatedAt""
                    FROM fps.tblsettings
                    WHERE fpsyear = {TargetFpsYear} AND id = {settingId}")
                .SingleAsync();

            Assert.Equal(settingValue, setting.Setting);
            Assert.Equal(settingNotes, setting.Notes);
            // The specific behavior this rewrite exists to prove: updated_by/updated_at come from
            // staging (the original confirmer's identity/timestamp), not the Worker's own.
            Assert.Equal(stagedUpdatedBy, setting.UpdatedBy);
            Assert.Equal(StagedUpdatedAt, setting.UpdatedAt);

            var monthHours = await assertContext.Database
                .SqlQuery<MaterializedMonthHours>($@"
                    SELECT year AS ""Year"", fmonth AS ""Fmonth"", days AS ""Days"", cvlhours AS ""CvlHours"", vidhours AS ""VidHours""
                    FROM fps.tlkpmonthhours
                    WHERE fpsyear = {TargetFpsYear} AND month = {month}")
                .SingleAsync();

            // The specific assertion that would catch year/fpsyear being accidentally swapped:
            // tlkpmonthhours.year must be the staged year (2031), not the target year (9091).
            Assert.Equal(year, monthHours.Year);
            // fmonth is copied through from staging, not recomputed by the Worker.
            Assert.Equal(fmonth, monthHours.Fmonth);
            Assert.Equal(days, monthHours.Days);
            Assert.Equal(cvlHours, monthHours.CvlHours);
            Assert.Equal(vidHours, monthHours.VidHours);

            // Materialize also clears staging — it's a singleton now, so leftover rows would either
            // collide with the next Confirm-upsert's PK or resurrect stale data into the next cycle.
            var settingsStagingRemaining = await assertContext.Database
                .SqlQuery<int>($@"SELECT COUNT(*)::int AS ""Value"" FROM fps.tblsettings_staging")
                .SingleAsync();
            var monthHoursStagingRemaining = await assertContext.Database
                .SqlQuery<int>($@"SELECT COUNT(*)::int AS ""Value"" FROM fps.tlkpmonthhours_staging")
                .SingleAsync();
            Assert.Equal(0, settingsStagingRemaining);
            Assert.Equal(0, monthHoursStagingRemaining);
        }
        finally
        {
            await using (var cleanupContext = CreateDbContext())
            {
                // Children before the fps.tblyearmaster parent, per the FK this test already proves is real.
                await cleanupContext.Database.ExecuteSqlInterpolatedAsync($@"
                    DELETE FROM fps.tblsettings WHERE fpsyear = {TargetFpsYear};");
                await cleanupContext.Database.ExecuteSqlInterpolatedAsync($@"
                    DELETE FROM fps.tlkpmonthhours WHERE fpsyear = {TargetFpsYear};");
                await cleanupContext.Database.ExecuteSqlInterpolatedAsync($@"
                    DELETE FROM fps.tblyearmaster WHERE fpsyear = {TargetFpsYear};");
            }

            // Unconditional and harmless whether materialize already cleared staging or the test failed
            // before it ran — a singleton table must never be left holding this test's rows.
            await ClearStagingAsync();
            await CleanupJobQueueAsync(jobQueueId);
        }
    }

    [SkippableFact]
    public async Task MaterializeStagedSettingsAsync_WhenStagedFpsYearDisagreesWithTarget_FailsClosedAndWritesNothing()
    {
        Skip.IfNot(CanRun(), _skipReason ?? "Integration DB unavailable.");

        const int targetFpsYear = 9094;
        const int wrongFpsYear = 9095;

        try
        {
            await using (var context = CreateDbContext())
            {
                await context.Database.ExecuteSqlInterpolatedAsync($@"
                    INSERT INTO fps.tblsettings_staging (id, setting, notes, fpsyear, updated_by, updated_at)
                    VALUES ('mismatch-guard-test', 'value', 'notes', {wrongFpsYear}, 'tester', {StagedUpdatedAt});");
            }

            var repository = CreateRepository();

            var ex = await Assert.ThrowsAsync<InvalidOperationException>(
                () => repository.MaterializeStagedSettingsAsync(targetFpsYear));

            Assert.Contains("tblsettings_staging", ex.Message, StringComparison.Ordinal);

            await using var assertContext = CreateDbContext();
            var liveRows = await assertContext.Database
                .SqlQuery<int>($@"SELECT COUNT(*)::int AS ""Value"" FROM fps.tblsettings WHERE fpsyear = {targetFpsYear}")
                .SingleAsync();
            Assert.Equal(0, liveRows);

            // Fail-closed happens before the clear step — the mismatched row is still there to inspect.
            var stagingRows = await assertContext.Database
                .SqlQuery<int>($@"SELECT COUNT(*)::int AS ""Value"" FROM fps.tblsettings_staging WHERE fpsyear = {wrongFpsYear}")
                .SingleAsync();
            Assert.Equal(1, stagingRows);
        }
        finally
        {
            await ClearStagingAsync();
        }
    }

    [SkippableFact]
    public async Task MaterializeStagedMonthHoursAsync_WhenStagedFpsYearDisagreesWithTarget_FailsClosedAndWritesNothing()
    {
        Skip.IfNot(CanRun(), _skipReason ?? "Integration DB unavailable.");

        const int targetFpsYear = 9096;
        const int wrongFpsYear = 9097;

        try
        {
            await using (var context = CreateDbContext())
            {
                await context.Database.ExecuteSqlInterpolatedAsync($@"
                    INSERT INTO fps.tlkpmonthhours_staging (year, month, fmonth, days, cvlhours, vidhours, fpsyear)
                    VALUES (2026, 1, 0, 20.0, 100.0, 50.0, {wrongFpsYear});");
            }

            var repository = CreateRepository();

            var ex = await Assert.ThrowsAsync<InvalidOperationException>(
                () => repository.MaterializeStagedMonthHoursAsync(targetFpsYear));

            Assert.Contains("tlkpmonthhours_staging", ex.Message, StringComparison.Ordinal);

            await using var assertContext = CreateDbContext();
            var liveRows = await assertContext.Database
                .SqlQuery<int>($@"SELECT COUNT(*)::int AS ""Value"" FROM fps.tlkpmonthhours WHERE fpsyear = {targetFpsYear}")
                .SingleAsync();
            Assert.Equal(0, liveRows);

            var stagingRows = await assertContext.Database
                .SqlQuery<int>($@"SELECT COUNT(*)::int AS ""Value"" FROM fps.tlkpmonthhours_staging WHERE fpsyear = {wrongFpsYear}")
                .SingleAsync();
            Assert.Equal(1, stagingRows);
        }
        finally
        {
            await ClearStagingAsync();
        }
    }

    [SkippableFact]
    public async Task MaterializeYearEndConfigurationStep_WhenPersistedTargetFpsYearDiffersFromContext_FailsClosedAndMaterializesNothing()
    {
        Skip.IfNot(CanRun(), _skipReason ?? "Integration DB unavailable.");

        var jobExecutionId = Guid.NewGuid();
        var jobQueueId = Guid.NewGuid();
        const int persistedTargetFpsYear = 9092;
        const int contextTargetFpsYear = 9093; // deliberately different — proves the live cross-check.

        await SeedJobQueueRowAsync(jobExecutionId, jobQueueId, BatchJobNames.YearEndDataSetup, persistedTargetFpsYear);

        try
        {
            var step = new MaterializeYearEndConfigurationStep(CreateRepository(), NullLogger<MaterializeYearEndConfigurationStep>.Instance);
            var context = new YearEndExecutionContext(jobExecutionId.ToString("D"), null, CurrentFpsYear: 2025, TargetFpsYear: contextTargetFpsYear);

            var ex = await Assert.ThrowsAsync<InvalidOperationException>(() => step.ExecuteAsync(context));

            Assert.Contains("Target year mismatch", ex.Message, StringComparison.Ordinal);
            Assert.Contains($"target_fpsyear={persistedTargetFpsYear}", ex.Message, StringComparison.Ordinal);
            Assert.Contains($"TargetFpsYear={contextTargetFpsYear}", ex.Message, StringComparison.Ordinal);

            // Fails before any table write — no fps.tblyearmaster row was seeded for either year, so a
            // materialize attempt on either would itself fail loudly (the FK this test suite already
            // proved is real). Confirming zero rows on both is the live proof it never got that far.
            await using var assertContext = CreateDbContext();
            var persistedYearRows = await assertContext.Database
                .SqlQuery<int>($@"SELECT COUNT(*)::int AS ""Value"" FROM fps.tblsettings WHERE fpsyear = {persistedTargetFpsYear}")
                .SingleAsync();
            var contextYearRows = await assertContext.Database
                .SqlQuery<int>($@"SELECT COUNT(*)::int AS ""Value"" FROM fps.tblsettings WHERE fpsyear = {contextTargetFpsYear}")
                .SingleAsync();
            Assert.Equal(0, persistedYearRows);
            Assert.Equal(0, contextYearRows);
        }
        finally
        {
            await CleanupJobQueueAsync(jobQueueId);
        }
    }

    private async Task SeedTargetYearMasterRowAsync(int targetFpsYear)
    {
        await using var context = CreateDbContext();
        await context.Database.ExecuteSqlInterpolatedAsync($@"
            INSERT INTO fps.tblyearmaster (fpsyear, fpsyearcode, yearstatus, remarks, active, createdby)
            VALUES ({targetFpsYear}, {$"FPS{targetFpsYear}-{(targetFpsYear + 1) % 100:D2}"}, 'Planned', 'Seeded by YearEndDataSetupRepositoryMaterializationIntegrationTests.', true, 'ws7-materialize-test');");
    }

    private async Task SeedJobQueueRowAsync(Guid jobExecutionId, Guid jobQueueId, string jobName, int? targetFpsYear)
    {
        await using var context = CreateDbContext();

        var jobId = await context.Database
            .SqlQuery<int>($@"SELECT jobid AS ""Value"" FROM fps.job_master WHERE jobname = {jobName}")
            .SingleAsync();

        var statusId = await context.Database
            .SqlQuery<int>($@"SELECT statusid AS ""Value"" FROM fps.job_status WHERE jobid = {jobId} LIMIT 1")
            .SingleAsync();

        await context.Database.ExecuteSqlInterpolatedAsync($@"
            INSERT INTO fps.job_queue
                (jobqueueid, jobexecutionid, jobid, statusid, requestedby, requested_at_utc, startdatetime, target_fpsyear)
            VALUES
                ({jobQueueId}, {jobExecutionId}, {jobId}, {statusId}, 'ws7-materialize-test', NOW(), NOW(), {targetFpsYear});");
    }

    private async Task CleanupJobQueueAsync(Guid jobQueueId)
    {
        await using var context = CreateDbContext();
        await context.Database.ExecuteSqlInterpolatedAsync($@"
            DELETE FROM fps.job_queue WHERE jobqueueid = {jobQueueId};");
    }

    // Staging is a singleton (no jobqueueid column any more) — every test that seeds it must clear it
    // unconditionally in its own finally block, win or lose, so a failed assertion never leaks rows into
    // a later test.
    private async Task ClearStagingAsync()
    {
        await using var context = CreateDbContext();
        await context.Database.ExecuteSqlRawAsync("DELETE FROM fps.tblsettings_staging;");
        await context.Database.ExecuteSqlRawAsync("DELETE FROM fps.tlkpmonthhours_staging;");
    }

    private IYearEndDataSetupRepository CreateRepository() => new YearEndDataSetupRepository(CreateDbContext());

    private BatchJobsDbContext CreateDbContext()
    {
        var options = new DbContextOptionsBuilder<BatchJobsDbContext>()
            .UseNpgsql(_connectionString)
            .Options;

        return new BatchJobsDbContext(options);
    }

    private bool CanRun() => string.IsNullOrWhiteSpace(_skipReason);

    private sealed class MaterializedSetting
    {
        public string Setting { get; init; } = null!;
        public string Notes { get; init; } = null!;
        public string UpdatedBy { get; init; } = null!;
        public DateTime UpdatedAt { get; init; }
    }

    private sealed class MaterializedMonthHours
    {
        public short Year { get; init; }
        public short Fmonth { get; init; }
        public decimal Days { get; init; }
        public decimal CvlHours { get; init; }
        public decimal VidHours { get; init; }
    }
}
