USE [MAB_Archive_CM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblFPSYearsToImport](
    [FPSName] [varchar](10) NOT NULL
,    CONSTRAINT [PK_tblYearsToImport] PRIMARY KEY NONCLUSTERED
    (
        FPSName
    )
) ON [PRIMARY]
GO
