--liquibase formatted sql

--changeset repo-admin:CR020 labels:ddl context:all

-- 1. Ensure the id column is NOT NULL (required for primary keys and identity)
ALTER TABLE mabarchive.tblstagingmilestone
  ALTER COLUMN id SET NOT NULL;

-- 2. Convert the column into an auto-incrementing identity column
ALTER TABLE mabarchive.tblstagingmilestone 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 3. Set the column as the Primary Key
ALTER TABLE mabarchive.tblstagingmilestone
  ADD CONSTRAINT pk_tblstagingmilestone_id PRIMARY KEY (id);

--ROLLBACK
--Not Applicable
