--liquibase formatted sql

--changeset repo-admin:CR032 labels:ddl context:all

ALTER TABLE fps.tblstagingmonthlytime
ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
);

UPDATE fps.tblstagingmonthlytime
SET id = DEFAULT
WHERE id IS NULL;

ALTER TABLE fps.tblstagingmonthlytime
ADD COLUMN IF NOT EXISTS filename character varying(255) COLLATE pg_catalog."default";

ALTER TABLE fps.tblstagingmonthlytime
ADD COLUMN IF NOT EXISTS importedby character varying(255) COLLATE pg_catalog."default";

ALTER TABLE fps.tblstagingmonthlytime
ADD COLUMN IF NOT EXISTS importeddate timestamp without time zone;

ALTER TABLE fps.tblstagingmonthlytime
ALTER COLUMN id SET NOT NULL;

ALTER TABLE fps.tblstagingmonthlytime
DROP CONSTRAINT IF EXISTS pk_tblstagingmonthlytime;

ALTER TABLE fps.tblstagingmonthlytime
ADD CONSTRAINT pk_tblstagingmonthlytime PRIMARY KEY (id);

--ROLLBACK
--Not Applicable