--liquibase formatted sql

--changeset repo-admin:CR041 labels:ddl context:all

ALTER TABLE fps.tblstagingmonthlyoutput
    ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN filename varchar(255),
    ADD COLUMN importedby varchar(255),
    ADD COLUMN importeddate timestamp without time zone,
    ALTER COLUMN id SET NOT NULL,
    ADD CONSTRAINT pk_tblstagingmonthlyoutput PRIMARY KEY (id);

--rollback ALTER TABLE fps.tblstagingmonthlyoutput DROP CONSTRAINT IF EXISTS pk_tblstagingmonthlyoutput;
--rollback ALTER TABLE fps.tblstagingmonthlyoutput DROP COLUMN IF EXISTS importeddate;
--rollback ALTER TABLE fps.tblstagingmonthlyoutput DROP COLUMN IF EXISTS importedby;
--rollback ALTER TABLE fps.tblstagingmonthlyoutput DROP COLUMN IF EXISTS filename;
--rollback ALTER TABLE fps.tblstagingmonthlyoutput DROP COLUMN IF EXISTS id;
