--liquibase formatted sql

--changeset repo-admin:CR063 labels:ProjectInvoiceStaging context:all splitStatements:false

-- CR063: Create staging table for project invoice data import and validation

CREATE TABLE IF NOT EXISTS fps.proj_invoice_staging
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 2147483647
        CACHE 1
    ),
    projectparent character varying(20) COLLATE pg_catalog."default",
    month character varying(10) COLLATE pg_catalog."default",
    amount character varying(10) COLLATE pg_catalog."default",
    costofwork character varying(10) COLLATE pg_catalog."default",
    wip character varying(10) COLLATE pg_catalog."default",
    profitloss character varying(10) COLLATE pg_catalog."default",
    detail character varying(255) COLLATE pg_catalog."default",
    type character varying(10) COLLATE pg_catalog."default",
    filename character varying(255) COLLATE pg_catalog."default",
    importedby character varying(255) COLLATE pg_catalog."default",
    importeddate timestamp without time zone,
    validationfailure text COLLATE pg_catalog."default",
    isexported boolean DEFAULT false,
    ispassed boolean DEFAULT false,

    CONSTRAINT pk_proj_invoice_staging PRIMARY KEY (id)
)
