--liquibase formatted sql

--changeset akshay:CR078 labels:ddl context:all splitStatements:false

DROP TABLE IF EXISTS fps.tblstagingmonthlytime;

CREATE TABLE fps.tblstagingmonthlytime
(
    pactstaffid     text,
    timecode        text,
    parentproject   text,
    month           double precision,
    workgroup       text,
    hours           double precision,
    failurecomments text,
    passed          boolean,
    pactid          text,
    newworkgroup    text,
    oldtestcode     text,
    name            text,
    id              integer GENERATED BY DEFAULT AS IDENTITY
                    (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
    filename        character varying(255),
    importedby      character varying(255),
    importeddate    timestamp without time zone,

    CONSTRAINT pk_tblstagingmonthlytime PRIMARY KEY (id)
);
