--liquibase formatted sql

--changeset akshay:CR079 labels:ddl context:all splitStatements:false

DROP TABLE IF EXISTS fps.tblstagingmonthlyoutput;

CREATE TABLE fps.tblstagingmonthlyoutput
(
    testcode       text,
    buyer          text,
    month          double precision,
    workgroup      text,
    volume         double precision,
    failurecomments text,
    passed         boolean,
    id             integer GENERATED BY DEFAULT AS IDENTITY
                   (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
    filename       character varying(255),
    importedby     character varying(255),
    importeddate   timestamp without time zone,

    CONSTRAINT pk_tblstagingmonthlyoutput PRIMARY KEY (id)
);
