--liquibase formatted sql

--changeset akshay:CR080 labels:ddl context:all splitStatements:false

DROP TABLE IF EXISTS fps.proj_invoice_staging;

CREATE TABLE fps.proj_invoice_staging
(
    id               integer GENERATED BY DEFAULT AS IDENTITY
                     (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
    projectparent    text,
    month            text,
    amount           text,
    costofwork       text,
    wip              text,
    profitloss       text,
    detail           text,
    type             text,
    filename         character varying(255),
    importedby       character varying(255),
    importeddate     timestamp without time zone,
    validationfailure text,
    isexported       boolean DEFAULT false,
    ispassed         boolean DEFAULT false,

    CONSTRAINT pk_proj_invoice_staging PRIMARY KEY (id)
);
