--liquibase formatted sql

--changeset arihant:CR088 labels:ddl context:all splitStatements:false

BEGIN;

-- ============================================================================
-- CR088
--
-- Purpose:
--   Restore the correct identity-sequence name for the surrogate id columns
--   Recreate Summaries writes to without supplying id:
--
--       fps.period_monthlyoutput.id
--       fps.period_timecostcalcs.id
--       fps.recreatesummaries_log.id (verification only -- see Findings)
--
-- Findings (live-verified 2026-09-22, across every environment checked):
--   - All three columns are genuine `GENERATED BY DEFAULT AS IDENTITY`
--     columns everywhere (attidentity = 'd'). None of them was ever a plain
--     column with a missing DEFAULT -- `column_default IS NULL` in
--     information_schema.columns is the normal, expected state for an
--     identity column, not evidence of damage. (An earlier pass at this CR
--     misread that as the defect and drafted an ALTER ... SET DEFAULT; a dry
--     run correctly rejected it with "column ... is an identity column" --
--     Postgres does not allow a plain DEFAULT alongside IDENTITY.)
--   - On any environment where period_monthlyoutput/period_timecostcalcs are
--     still un-partitioned, and on recreatesummaries_log everywhere, the
--     identity column already resolves, via pg_get_serial_sequence(), to the
--     conventional fps.<table>_id_seq name, already positioned safely
--     ahead of MAX(id). These are NOT broken -- the migration step
--     (Section 1) is a verified no-op there. The contract test (Section 3)
--     still runs everywhere, including these cases, and will consume one
--     identity value from each table it touches -- a harmless forward gap,
--     not evidence these were changed.
--   - Any environment where CR084 (period_monthlyoutput) and CR082
--     (period_timecostcalcs) have already been applied IS broken, but not
--     by a missing sequence: those migrations built the partitioned
--     replacement via
--     `CREATE TABLE fps.<table>_p (LIKE fps.<table> INCLUDING ALL) PARTITION
--     BY LIST (fpsyear)`. INCLUDING ALL includes IDENTITY, so Postgres
--     auto-generated a brand-new backing sequence named after the temporary
--     table -- fps.period_monthlyoutput_p_id_seq /
--     fps.period_timecostcalcs_p_id_seq -- and it was never renamed after
--     the table swap (`ALTER TABLE ..._p RENAME TO <table>`). The original,
--     conventionally-named sequence went down later when the retained
--     `<table>_old` backup was eventually dropped (confirmed gone on every
--     affected environment checked). RefreshPeriodMoStep / RefreshPeriodTccStep
--     hardcode `setval('fps.<table>_id_seq', ...)` before their INSERT, so
--     they fail with 42P01 (relation does not exist) before ever reaching the
--     insert -- exactly the live failure seen triggering RecreateSummary
--     for period 5 / 2025 on one such environment.
--   - The orphaned fps.period_monthlyoutput_p_id_seq /
--     fps.period_timecostcalcs_p_id_seq sequences are otherwise completely
--     healthy and still the column's real identity sequence (confirmed via
--     pg_get_serial_sequence) -- but found sitting well behind the table's
--     real MAX(id) on every affected environment checked. A rename alone,
--     with no resync, would silently set up the very next real insert to
--     collide with existing data.
--
-- Correction, generic across all three tables (safe to run identically on
-- every environment -- a no-op wherever nothing is actually wrong):
--   1. Resolve the column's real backing sequence via
--      pg_get_serial_sequence() -- never assume a name.
--   2. If that name does not already match the conventional
--      fps.<table>_id_seq the application code hardcodes, rename it into
--      place -- guarded: fail closed with a specific diagnostic if a
--      different object already occupies the expected name, rather than
--      surfacing Postgres's generic "relation already exists" error.
--      Renaming a sequence does not disturb Postgres's internal identity
--      linkage (tracked by OID, not name).
--   3. Advance-only sync: only move the sequence forward if it is currently
--      behind the table's data, using ALTER SEQUENCE ... RESTART WITH
--      (transactional -- rolls back cleanly with everything else in this
--      migration if a later step fails) rather than setval() (deliberately
--      non-transactional in Postgres -- it would survive a rollback and
--      silently leave the sequence advanced even on a failed run). Never
--      move an already-safe sequence backward.
--   4. Validate with a real INSERT that omits id, proving the identity
--      column actually generates a non-null id. The inserted row is rolled
--      back to a SAVEPOINT before COMMIT, but the identity value it
--      consumed is NOT restored -- nextval() is also non-transactional, so
--      this test leaves a small, harmless forward gap in every sequence it
--      touches, on every environment, even where the migration itself did
--      nothing. Do not try to close that gap afterward -- gaps in identity
--      sequences are normal. Catalog metadata alone would not have caught
--      either the original defect or a wrong fix -- both were only visible
--      by actually exercising the contract.
--
-- Scope note:
--   fps.period_proj_subcontract (CR083) and fps.projectmonthcasework (CR085)
--   were reviewed and use composite natural keys with no surrogate id column
--   -- not affected. The other Recreate Summaries write targets --
--   fps.projectmonth, projectmonth2, projectmonth3, projectmonthfinal and
--   fps.timecostcalcs -- were also reviewed (EF model + live catalog) and
--   are all composite-natural-key tables with no surrogate id column either
--   -- also not affected. Only the three tables above have a surrogate id.
-- ============================================================================


-- ============================================================================
-- 0. Preconditions
-- ============================================================================

DO $$
DECLARE
    v_table text;
BEGIN

    FOREACH v_table IN ARRAY ARRAY['period_monthlyoutput', 'period_timecostcalcs', 'recreatesummaries_log']
    LOOP

        IF to_regclass('fps.' || v_table) IS NULL THEN
            RAISE EXCEPTION 'CR088 precondition failed: fps.% does not exist.', v_table;
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'fps' AND table_name = v_table AND column_name = 'id'
        ) THEN
            RAISE EXCEPTION 'CR088 precondition failed: fps.%.id does not exist.', v_table;
        END IF;

        IF pg_get_serial_sequence('fps.' || v_table, 'id') IS NULL THEN
            RAISE EXCEPTION 'CR088 precondition failed: fps.%.id has no identity/serial-backed sequence at all -- this CR only repairs a misnamed/behind sequence, it does not create identity from scratch.', v_table;
        END IF;

    END LOOP;

END
$$;


-- Prevent concurrent Recreate Summaries writes while sequences are renamed/resynced.
LOCK TABLE
    fps.period_monthlyoutput,
    fps.period_timecostcalcs,
    fps.recreatesummaries_log
IN ACCESS EXCLUSIVE MODE;


-- ============================================================================
-- 1. Rename any misnamed backing sequence into place, then advance-only sync
-- ============================================================================

DO $$
DECLARE
    v_table         text;
    v_real_seq      text;
    v_expected_seq  text;
    v_max_id        bigint;
    v_next_value    bigint;
BEGIN

    FOREACH v_table IN ARRAY ARRAY['period_monthlyoutput', 'period_timecostcalcs', 'recreatesummaries_log']
    LOOP

        v_real_seq     := pg_get_serial_sequence('fps.' || v_table, 'id');
        v_expected_seq := 'fps.' || v_table || '_id_seq';

        IF v_real_seq <> v_expected_seq THEN

            -- Fail closed with a specific diagnostic if a different object
            -- already occupies the conventional name, rather than
            -- surfacing Postgres's generic "relation already exists" error.
            IF to_regclass(v_expected_seq) IS NOT NULL THEN
                RAISE EXCEPTION 'CR088 cannot rename % to % -- % already exists and is not the current sequence for fps.%.id.', v_real_seq, v_expected_seq, v_expected_seq, v_table;
            END IF;

            RAISE NOTICE 'CR088: renaming % to % for fps.%.id', v_real_seq, v_table || '_id_seq', v_table;

            EXECUTE format('ALTER SEQUENCE %s RENAME TO %I', v_real_seq, v_table || '_id_seq');
            v_real_seq := v_expected_seq;

        END IF;

        EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM fps.%I', v_table)
            INTO v_max_id;

        EXECUTE format('SELECT last_value + CASE WHEN is_called THEN 1 ELSE 0 END FROM %s', v_real_seq)
            INTO v_next_value;

        -- Advance-only: only move the sequence forward if it is currently
        -- behind the table's data. An already-safe sequence is left exactly
        -- where it is.
        -- ALTER SEQUENCE ... RESTART WITH is used instead of setval()
        -- deliberately: RESTART WITH is transactional DDL and rolls back
        -- cleanly with the rest of this changeset if a later step fails;
        -- setval() is explicitly non-transactional in Postgres and would
        -- survive a rollback, silently leaving the sequence advanced.
        IF v_next_value <= v_max_id THEN

            RAISE NOTICE 'CR088: advancing % from next-value % to % (MAX(id)+1) for fps.%.id', v_real_seq, v_next_value, v_max_id + 1, v_table;

            EXECUTE format('ALTER SEQUENCE %s RESTART WITH %s', v_real_seq, GREATEST(v_max_id + 1, 1));

        END IF;

    END LOOP;

END
$$;


-- ============================================================================
-- 2. Postconditions -- catalog checks
-- ============================================================================

DO $$
DECLARE
    v_table       text;
    v_real_seq    text;
    v_max_id      bigint;
    v_next_value  bigint;
    v_identity    text;
BEGIN

    FOREACH v_table IN ARRAY ARRAY['period_monthlyoutput', 'period_timecostcalcs', 'recreatesummaries_log']
    LOOP

        -- Column must still be a genuine identity column (this CR must never
        -- turn an identity column into anything else).
        SELECT a.attidentity::text INTO v_identity
        FROM pg_attribute a
        WHERE a.attrelid = ('fps.' || v_table)::regclass AND a.attname = 'id';

        IF v_identity NOT IN ('a', 'd') THEN
            RAISE EXCEPTION 'CR088 postcondition failed: fps.%.id is no longer an identity column (attidentity=%).', v_table, v_identity;
        END IF;

        -- Real backing sequence must now match the conventional name the
        -- application code hardcodes.
        v_real_seq := pg_get_serial_sequence('fps.' || v_table, 'id');

        IF v_real_seq IS DISTINCT FROM ('fps.' || v_table || '_id_seq') THEN
            RAISE EXCEPTION 'CR088 postcondition failed: fps.%.id backing sequence is % -- expected fps.%_id_seq.', v_table, v_real_seq, v_table;
        END IF;

        -- Sequence must not be behind existing data (would collide on first insert).
        EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM fps.%I', v_table)
            INTO v_max_id;

        EXECUTE format('SELECT last_value + CASE WHEN is_called THEN 1 ELSE 0 END FROM %s', v_real_seq)
            INTO v_next_value;

        IF v_next_value <= v_max_id THEN
            RAISE EXCEPTION 'CR088 postcondition failed: % next value (%) would collide with existing MAX(id) (%) on fps.%.', v_real_seq, v_next_value, v_max_id, v_table;
        END IF;

    END LOOP;

END
$$;


-- ============================================================================
-- 3. Postconditions -- live contract test
--
-- Catalog metadata alone would not have caught either the original defect
-- (a genuinely healthy-looking identity column pointing at the wrong-named
-- sequence) or a wrong fix (this CR's own first draft, which a dry run
-- caught trying to SET DEFAULT on an identity column). Prove the actual
-- contract Recreate Summaries depends on: an INSERT that omits id must
-- produce a non-null, DB-generated id. The inserted row is rolled back to a
-- SAVEPOINT before COMMIT. The identity value it consumed is NOT restored --
-- nextval() is explicitly non-transactional in Postgres (documented
-- behavior, not a bug), so this test leaves a small, harmless forward gap in
-- every sequence it touches, on every environment it runs against,
-- including any table/environment combination where the migration itself is
-- a no-op. Do not try to reset a sequence backward afterward to close that
-- gap -- gaps in identity sequences are normal and expected.
-- ============================================================================

SAVEPOINT cr088_contract_test;

DO $$
DECLARE
    v_table_name  text;
    v_column_list text;
    v_value_list  text;
    v_dummy_value text;
    v_sql         text;
    v_test_id     integer;
    rec           record;
BEGIN

    FOREACH v_table_name IN ARRAY ARRAY['period_monthlyoutput', 'period_timecostcalcs', 'recreatesummaries_log']
    LOOP

        v_column_list := '';
        v_value_list  := '';

        -- Build a minimal valid row from live catalog metadata: every NOT
        -- NULL, no-default column except id gets a short, type-appropriate
        -- dummy value. Deliberately not a hardcoded column list -- on
        -- environments where CR084/CR082 have already run, period_monthlyoutput
        -- and period_timecostcalcs have an extra NOT NULL fpsyear column that
        -- un-migrated environments don't have yet; this discovers whatever the
        -- target environment actually has at run time.
        FOR rec IN
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_schema = 'fps'
              AND table_name = v_table_name
              AND column_name <> 'id'
              AND is_nullable = 'NO'
              AND column_default IS NULL
            ORDER BY ordinal_position
        LOOP

            v_dummy_value := CASE
                -- fpsyear carries a real FK to fps.tblyearmaster on some of
                -- these tables (recreatesummaries_log, confirmed live) but
                -- not others (period_monthlyoutput/period_timecostcalcs,
                -- per CR082/CR084) -- pull a real valid year rather than
                -- assuming either shape.
                WHEN rec.column_name = 'fpsyear' THEN '(SELECT fpsyear FROM fps.tblyearmaster LIMIT 1)'
                WHEN rec.data_type IN ('character varying', 'text', 'character') THEN quote_literal('X')
                WHEN rec.data_type IN ('smallint', 'integer', 'bigint', 'numeric', 'double precision', 'real', 'money') THEN '-1'
                WHEN rec.data_type = 'boolean' THEN 'false'
                WHEN rec.data_type = 'date' THEN quote_literal(current_date::text)
                WHEN rec.data_type LIKE 'timestamp%' THEN quote_literal(now()::text)
                ELSE NULL
            END;

            IF v_dummy_value IS NULL THEN
                RAISE EXCEPTION 'CR088 contract test: no dummy-value rule for fps.%.% (data_type %). Extend the test before proceeding -- do not skip the column.', v_table_name, rec.column_name, rec.data_type;
            END IF;

            v_column_list := v_column_list || quote_ident(rec.column_name) || ', ';
            v_value_list  := v_value_list || v_dummy_value || ', ';

        END LOOP;

        v_column_list := left(v_column_list, length(v_column_list) - 2);
        v_value_list  := left(v_value_list, length(v_value_list) - 2);

        v_sql := format('INSERT INTO fps.%I (%s) VALUES (%s) RETURNING id', v_table_name, v_column_list, v_value_list);

        EXECUTE v_sql INTO v_test_id;

        IF v_test_id IS NULL THEN
            RAISE EXCEPTION 'CR088 contract test failed: fps.%.id was NULL after an INSERT omitting id.', v_table_name;
        END IF;

        RAISE NOTICE 'CR088 contract test passed for fps.%: generated id = %', v_table_name, v_test_id;

    END LOOP;

END
$$;

ROLLBACK TO SAVEPOINT cr088_contract_test;


COMMIT;


--rollback -- No data-destructive change was made: this CR only renames an
--rollback -- already-existing sequence and/or advances its position forward.
--rollback -- There is no safe automated rollback for "rename it back" once
--rollback -- new rows may have been generated against the corrected name;
--rollback -- treat this as forward-only. If it must be undone before any
--rollback -- new inserts have occurred, manually reverse the specific
--rollback -- ALTER SEQUENCE ... RENAME TO ... reported by this run's RAISE
--rollback -- NOTICE output.


-- ============================================================================
-- IMPORTANT
-- ============================================================================
--
-- This CR does not create any new database object, does not change any
-- existing row's id, and does not touch period_proj_subcontract or
-- projectmonthcasework (composite natural keys, no surrogate id -- confirmed
-- not affected). The migration itself (Section 1: rename / RESTART WITH) is
-- expected to be a verified no-op wherever the identity sequence is already
-- correctly named and positioned, and on recreatesummaries_log everywhere --
-- the RAISE NOTICE lines make it explicit which environments actually
-- needed it. The live contract test (Section 3) still runs everywhere and
-- advances each table's sequence by exactly one, even where the migration
-- did nothing -- a harmless, expected side effect of proving the contract
-- for real, not evidence of an unintended change.
-- ============================================================================
