--liquibase formatted sql

--changeset akshay:CR081 labels:ddl context:all splitStatements:false

DROP TABLE IF EXISTS fps.proj_subcontract_staging;

CREATE TABLE fps.proj_subcontract_staging
(
    id               integer GENERATED BY DEFAULT AS IDENTITY
                     (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
    project          text,
    testjob          text,
    month            text,
    amount           text,
    workgroup        text,
    acctcode         text,
    supplier         text,
    description      text,
    suppliernumber   text,
    dailyrate        text,
    animaldays       text,
    filename         character varying(255),
    importedby       character varying(255),
    importeddate     timestamp without time zone,
    validationfailure text,
    isexported       boolean DEFAULT false,
    ispassed         boolean DEFAULT false,

    CONSTRAINT pk_proj_subcontract_staging PRIMARY KEY (id)
);
