using Apha.BatchJobs.Domain.Entities;
using Apha.BatchJobs.Domain.Interfaces;
using Apha.BatchJobs.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace Apha.BatchJobs.Infrastructure.Repositories;

/// <summary>
/// Implementation of batch lock repository using EF Core.
/// </summary>
public class BatchLockRepository : IBatchLockRepository
{
    private readonly BatchJobsDbContext _context;

    /// <summary>
    /// Initializes a new instance of the BatchLockRepository.
    /// </summary>
    /// <param name="context">The database context.</param>
    public BatchLockRepository(BatchJobsDbContext context)
    {
        _context = context ?? throw new ArgumentNullException(nameof(context));
    }

    /// <inheritdoc />
    public async Task<bool> TryAcquireLockAsync(string jobName, string runId, int timeoutSeconds, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(jobName))
            throw new ArgumentException("Job name cannot be null or empty.", nameof(jobName));

        if (string.IsNullOrWhiteSpace(runId))
            throw new ArgumentException("Run ID cannot be null or empty.", nameof(runId));

        // Clean up expired locks
        var now = DateTime.UtcNow;
        var expiredLocks = await _context.BatchLocks
            .Where(l => l.JobName == jobName && l.ExpiresAt < now)
            .ToListAsync(cancellationToken);

        if (expiredLocks.Any())
        {
            _context.BatchLocks.RemoveRange(expiredLocks);
            await _context.SaveChangesAsync(cancellationToken);
        }

        // Check for active lock
        var activeLock = await _context.BatchLocks
            .FirstOrDefaultAsync(l => l.JobName == jobName && l.IsActive, cancellationToken);

        if (activeLock != null)
            return false; // Lock already held by another process

        // Create new lock
        var newLock = new BatchLock
        {
            LockId = 0, // auto-generated by database
            JobName = jobName,
            RunId = runId,
            AcquiredAt = now,
            ExpiresAt = now.AddSeconds(timeoutSeconds),
            IsActive = true
        };

        _context.BatchLocks.Add(newLock);
        await _context.SaveChangesAsync(cancellationToken);

        return true;
    }

    /// <inheritdoc />
    public async Task ReleaseLockAsync(string jobName, string runId, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(jobName))
            throw new ArgumentException("Job name cannot be null or empty.", nameof(jobName));

        if (string.IsNullOrWhiteSpace(runId))
            throw new ArgumentException("Run ID cannot be null or empty.", nameof(runId));

        var lockToRelease = await _context.BatchLocks
            .FirstOrDefaultAsync(l => l.JobName == jobName && l.RunId == runId, cancellationToken);

        if (lockToRelease != null)
        {
            _context.BatchLocks.Remove(lockToRelease);
            await _context.SaveChangesAsync(cancellationToken);
        }
    }

    /// <inheritdoc />
    public async Task<BatchLock?> GetActiveLockAsync(string jobName, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(jobName))
            throw new ArgumentException("Job name cannot be null or empty.", nameof(jobName));

        var now = DateTime.UtcNow;
        return await _context.BatchLocks
            .FirstOrDefaultAsync(l => l.JobName == jobName && l.IsActive && l.ExpiresAt > now, cancellationToken);
    }
}
