/*
 * TRANSFORMENGINE MIGRATION — AccessSystemMap.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 4 — DataAccess Layer - DbContext + Map Files + Repository (Steps 7-7a)
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - New IEntityTypeConfiguration<AccessSystem> map for mabarchive.tblaccesssystems
 *   - Single integer PK systemid — ValueGeneratedNever() (no identity per DDL)
 *   - All columns mapped with lowercase HasColumnName() as per project convention
 *
 * PRESERVED:
 *   - All column names and constraints from PostgreSQL DDL (mabarchive.tblaccesssystems)
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - none — fully automated.
 */
using Apha.PIMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Apha.PIMS.DataAccess.Data
{
    // TRANSFORMENGINE: maps mabarchive.tblaccesssystems; single integer PK (systemid), not identity
    public class AccessSystemMap : IEntityTypeConfiguration<AccessSystem>
    {
        public void Configure(EntityTypeBuilder<AccessSystem> entity)
        {
            entity.HasKey(e => e.Systemid).HasName("pk_tblaccesssystems");

            entity.ToTable("tblaccesssystems", "mabarchive");

            // TRANSFORMENGINE: systemid is NOT GENERATED BY DEFAULT — ValueGeneratedNever
            entity.Property(e => e.Systemid)
                .ValueGeneratedNever()
                .HasColumnName("systemid");

            entity.Property(e => e.Systemname)
                .HasMaxLength(50)
                .HasColumnName("systemname");
        }
    }
}
