/*
 * TRANSFORMENGINE MIGRATION — FrequencyMap.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 4 — DataAccess Layer - DbContext + Map Files + Repository (Steps 7-7a)
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - New IEntityTypeConfiguration<Frequency> map for mabarchive.tlkpfrequency
 *   - Single integer PK frequencyid — ValueGeneratedNever() (no identity per DDL)
 *   - DDL column 'frequency' maps to entity property FrequencyValue (aliased to avoid name clash)
 *   - All columns mapped with lowercase HasColumnName() as per project convention
 *
 * PRESERVED:
 *   - All column names and constraints from PostgreSQL DDL (mabarchive.tlkpfrequency)
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - none — fully automated.
 */
using Apha.PIMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Apha.PIMS.DataAccess.Data
{
    // TRANSFORMENGINE: maps mabarchive.tlkpfrequency; lookup table; PK=frequencyid; DDL 'frequency' → FrequencyValue
    public class FrequencyMap : IEntityTypeConfiguration<Frequency>
    {
        public void Configure(EntityTypeBuilder<Frequency> entity)
        {
            entity.HasKey(e => e.Frequencyid).HasName("pk_tlkpfrequency");

            entity.ToTable("tlkpfrequency", "mabarchive");

            // TRANSFORMENGINE: frequencyid is NOT GENERATED BY DEFAULT — ValueGeneratedNever
            entity.Property(e => e.Frequencyid)
                .ValueGeneratedNever()
                .HasColumnName("frequencyid");

            // TRANSFORMENGINE: DDL column name 'frequency' — entity property FrequencyValue
            entity.Property(e => e.FrequencyValue)
                .HasMaxLength(50)
                .HasColumnName("frequency");
        }
    }
}
