// TRANSFORMENGINE: human_review — verify before running

/*
 * TRANSFORMENGINE MIGRATION — RadTrackInvoiceMap.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 4 — DataAccess Layer - DbContext + Map Files + Repository (Steps 7-7a)
 * Migrated : 2026-06-12
 *
 * CHANGED:
 *   - New file: IEntityTypeConfiguration<RadTrackInvoice> derived from
 *     source/pgsql/mab_archive/Tables/tblradtrackinvoice.sql DDL.
 *   - HasColumnName() arguments are all lowercase, matching PostgreSQL column names per Phase 4 rule.
 *   - ToTable("tblradtrackinvoice", "mabarchive") — schema and table name lowercase per DDL.
 *   - invoicecounter is integer GENERATED BY DEFAULT AS IDENTITY — mapped with ValueGeneratedOnAdd().
 *   - invoicepaid is smallint NOT NULL DEFAULT 0 — mapped with HasDefaultValue((short)0).
 *   - Timestamp columns given explicit HasColumnType("timestamp without time zone") to match DDL exactly.
 *   - FK constraints noted in DDL (fk_tblradtrackinvoice_g_tlkpproject_radtrackdata,
 *     fk_tblradtrackinvoice_tblradtrackcontract) are present in the database schema; navigation
 *     properties intentionally omitted at the map/entity layer (Core-clean rule).
 *
 * PRESERVED:
 *   - All 11 column names from DDL retained verbatim as lowercase HasColumnName values.
 *   - PK constraint name pk_tblradtrackinvoice from DDL.
 *   - Column lengths: project varchar(20), contract varchar(10), invoiceref varchar(50).
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - TRANSFORMENGINE TODO: Verify invoicepaid short (smallint) mapping is acceptable or should
 *     be mapped to bool — tracked in checklist. Changing type requires entity + DDL column update.
 */

using Apha.PIMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Apha.PIMS.DataAccess.Data
{
    public class RadTrackInvoiceMap : IEntityTypeConfiguration<RadTrackInvoice>
    {
        public void Configure(EntityTypeBuilder<RadTrackInvoice> entity)
        {
            // TRANSFORMENGINE: PK — invoicecounter, constraint name from DDL.
            entity.HasKey(e => e.InvoiceCounter).HasName("pk_tblradtrackinvoice");

            // TRANSFORMENGINE: Target table mabarchive.tblradtrackinvoice — lowercase per rule.
            entity.ToTable("tblradtrackinvoice", "mabarchive");

            // TRANSFORMENGINE: invoicecounter — integer GENERATED BY DEFAULT AS IDENTITY; auto-generated on insert.
            entity.Property(e => e.InvoiceCounter)
                .HasColumnName("invoicecounter")
                .ValueGeneratedOnAdd();

            // TRANSFORMENGINE: project — character varying(20); nullable; FK to g_tlkpproject_radtrackdata(parentproject).
            entity.Property(e => e.Project)
                .HasMaxLength(20)
                .HasColumnName("project");

            // TRANSFORMENGINE: plannedamount — double precision; nullable in DDL.
            entity.Property(e => e.PlannedAmount)
                .HasColumnName("plannedamount");

            // TRANSFORMENGINE: dueamount — double precision; nullable in DDL.
            entity.Property(e => e.DueAmount)
                .HasColumnName("dueamount");

            // TRANSFORMENGINE: duedate — timestamp without time zone; nullable in DDL.
            entity.Property(e => e.DueDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("duedate");

            // TRANSFORMENGINE: actualamount — double precision; nullable in DDL.
            entity.Property(e => e.ActualAmount)
                .HasColumnName("actualamount");

            // TRANSFORMENGINE: dateinvoiced — timestamp without time zone; nullable in DDL.
            entity.Property(e => e.DateInvoiced)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("dateinvoiced");

            // TRANSFORMENGINE: contract — character varying(10); nullable; FK to tblradtrackcontract(contract).
            entity.Property(e => e.Contract)
                .HasMaxLength(10)
                .HasColumnName("contract");

            // TRANSFORMENGINE: datejobsheetraised — timestamp without time zone; nullable in DDL.
            entity.Property(e => e.DateJobsheetRaised)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("datejobsheetraised");

            // TRANSFORMENGINE: invoiceref — character varying(50); nullable in DDL.
            entity.Property(e => e.InvoiceRef)
                .HasMaxLength(50)
                .HasColumnName("invoiceref");

            // TRANSFORMENGINE: invoicepaid — smallint NOT NULL DEFAULT 0; kept as short to mirror DDL type exactly.
            // TRANSFORMENGINE TODO: Evaluate whether bool is preferred — see checklist.
            entity.Property(e => e.InvoicePaid)
                .HasDefaultValue((short)0)
                .HasColumnName("invoicepaid");
        }
    }
}
