/*
 * TRANSFORMENGINE MIGRATION — ReportGroupMap.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 4 — DataAccess Layer - DbContext + Map Files + Repository (Steps 7-7a)
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - New IEntityTypeConfiguration<ReportGroup> map for mabarchive.tblreportgroup
 *   - PK groupid mapped with ValueGeneratedOnAdd() — GENERATED BY DEFAULT AS IDENTITY per DDL
 *   - All columns mapped with lowercase HasColumnName() as per project convention
 *
 * PRESERVED:
 *   - All column names and constraints from PostgreSQL DDL (mabarchive.tblreportgroup)
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - none — fully automated.
 */
using Apha.PIMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Apha.PIMS.DataAccess.Data
{
    // TRANSFORMENGINE: maps mabarchive.tblreportgroup; PK=groupid (GENERATED BY DEFAULT AS IDENTITY)
    public class ReportGroupMap : IEntityTypeConfiguration<ReportGroup>
    {
        public void Configure(EntityTypeBuilder<ReportGroup> entity)
        {
            entity.HasKey(e => e.Groupid).HasName("pk_tblreportgroup");

            entity.ToTable("tblreportgroup", "mabarchive");

            // TRANSFORMENGINE: GENERATED BY DEFAULT AS IDENTITY — ValueGeneratedOnAdd
            entity.Property(e => e.Groupid)
                .ValueGeneratedOnAdd()
                .HasColumnName("groupid");

            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .HasColumnName("description");
        }
    }
}
