/*
 * TRANSFORMENGINE MIGRATION — ReportMap.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 4 — DataAccess Layer - DbContext + Map Files + Repository (Steps 7-7a)
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - New IEntityTypeConfiguration<Report> map for mabarchive.tblreport
 *   - PK id mapped with ValueGeneratedNever() — not identity-generated per DDL
 *   - All columns mapped with lowercase HasColumnName() as per project convention
 *   - type char(1) mapped as string with fixed length 1
 *
 * PRESERVED:
 *   - All column names and constraints from PostgreSQL DDL (mabarchive.tblreport)
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - TRANSFORMENGINE TODO: verify 'type' char(1) column — confirm no enum mapping needed
 */
using Apha.PIMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Apha.PIMS.DataAccess.Data
{
    // TRANSFORMENGINE: maps mabarchive.tblreport; PK=id (not identity); type is char(1) stored as string
    public class ReportMap : IEntityTypeConfiguration<Report>
    {
        public void Configure(EntityTypeBuilder<Report> entity)
        {
            entity.HasKey(e => e.Id).HasName("pk_tblreport");

            entity.ToTable("tblreport", "mabarchive");

            // TRANSFORMENGINE: id is NOT GENERATED BY DEFAULT — ValueGeneratedNever
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Reportname)
                .HasMaxLength(50)
                .HasColumnName("reportname");

            entity.Property(e => e.Reportdescription)
                .HasMaxLength(50)
                .HasColumnName("reportdescription");

            entity.Property(e => e.Filter)
                .HasMaxLength(200)
                .HasColumnName("filter");

            entity.Property(e => e.Mailcomment)
                .HasMaxLength(250)
                .HasColumnName("mailcomment");

            entity.Property(e => e.Mailtitle)
                .HasMaxLength(50)
                .HasColumnName("mailtitle");

            entity.Property(e => e.Emailable)
                .HasColumnName("emailable");

            entity.Property(e => e.Sortorder)
                .HasColumnName("sortorder");

            entity.Property(e => e.Allowpickprogramme)
                .HasColumnName("allowpickprogramme");

            entity.Property(e => e.Allowpickproject)
                .HasColumnName("allowpickproject");

            entity.Property(e => e.Allowpickmanager)
                .HasColumnName("allowpickmanager");

            entity.Property(e => e.Allowpickcontract)
                .HasColumnName("allowpickcontract");

            entity.Property(e => e.Allowpickcustomer)
                .HasColumnName("allowpickcustomer");

            entity.Property(e => e.Allowpickmonth)
                .HasColumnName("allowpickmonth");

            entity.Property(e => e.Allowpickfyear)
                .HasColumnName("allowpickfyear");

            entity.Property(e => e.Reporthelp)
                .HasMaxLength(250)
                .HasColumnName("reporthelp");

            // TRANSFORMENGINE: char(1) in PostgreSQL — fixed-length string
            entity.Property(e => e.Type)
                .HasMaxLength(1)
                .IsFixedLength()
                .HasColumnName("type");
        }
    }
}
