/*
 * TRANSFORMENGINE MIGRATION — ReviewItemMap.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 4 — DataAccess Layer - DbContext + Map Files + Repository (Steps 7-7a)
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - New IEntityTypeConfiguration<ReviewItem> map for mabarchive.tlkpreviewitem
 *   - Single integer PK itemid — ValueGeneratedNever() (no identity per DDL)
 *   - All columns mapped with lowercase HasColumnName() as per project convention
 *
 * PRESERVED:
 *   - All column names and constraints from PostgreSQL DDL (mabarchive.tlkpreviewitem)
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - none — fully automated.
 */
using Apha.PIMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Apha.PIMS.DataAccess.Data
{
    // TRANSFORMENGINE: maps mabarchive.tlkpreviewitem; lookup table; PK=itemid (not identity)
    public class ReviewItemMap : IEntityTypeConfiguration<ReviewItem>
    {
        public void Configure(EntityTypeBuilder<ReviewItem> entity)
        {
            entity.HasKey(e => e.Itemid).HasName("pk_tlkpreviewitem");

            entity.ToTable("tlkpreviewitem", "mabarchive");

            // TRANSFORMENGINE: itemid is NOT GENERATED BY DEFAULT — ValueGeneratedNever
            entity.Property(e => e.Itemid)
                .ValueGeneratedNever()
                .HasColumnName("itemid");

            entity.Property(e => e.Item)
                .HasMaxLength(50)
                .HasColumnName("item");
        }
    }
}
