/*
 * TRANSFORMENGINE MIGRATION — FrequencyService.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 3 — Application Layer - DTOs + Service Interfaces + EntityMapper + Services (Steps 4-6)
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - New Application service implementing IFrequencyService for Frequency CRUD (Other Tab lookup management, frmMaintainance)
 *   - Single integer PK (frequencyid) — GENERATED BY DEFAULT AS IDENTITY
 *   - Delegates all persistence to IFrequencyRepository; no direct DbContext usage
 *   - All methods are async end-to-end
 *   - Throws ArgumentException on null/invalid input; KeyNotFoundException when entity not found
 *   - AutoMapper used for all entity <-> DTO conversions
 *
 * PRESERVED:
 *   - All business guards: null-input validation, not-found checks before update/delete
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - none — fully automated.
 */

using Apha.PIMS.Application.Dtos;
using Apha.PIMS.Application.Interfaces;
using Apha.PIMS.Core.Entities;
using Apha.PIMS.Core.Interfaces;
using AutoMapper;

namespace Apha.PIMS.Application.Services
{
    // TRANSFORMENGINE: service orchestrates IFrequencyRepository; single integer PK (frequencyid); lookup/reference table
    public class FrequencyService : IFrequencyService
    {
        private readonly IFrequencyRepository _repository;
        private readonly IMapper _mapper;

        public FrequencyService(IFrequencyRepository repository, IMapper mapper)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        // TRANSFORMENGINE: returns full list for frequency dropdown / lookup usage
        public async Task<List<FrequencyDto>> GetAllAsync()
        {
            List<Frequency> entities = await _repository.GetAllAsync();
            return _mapper.Map<List<FrequencyDto>>(entities);
        }

        // TRANSFORMENGINE: returns nullable — controller maps null to 404; single integer PK lookup
        public async Task<FrequencyDto?> GetByIdAsync(int frequencyid)
        {
            Frequency? entity = await _repository.GetByIdAsync(frequencyid);
            return entity is null ? null : _mapper.Map<FrequencyDto>(entity);
        }

        // TRANSFORMENGINE: validate non-null DTO before first await
        public async Task<FrequencyDto> CreateAsync(FrequencyDto dto)
        {
            if (dto is null) throw new ArgumentNullException(nameof(dto));

            Frequency entity = _mapper.Map<Frequency>(dto);
            Frequency created = await _repository.AddAsync(entity);
            return _mapper.Map<FrequencyDto>(created);
        }

        // TRANSFORMENGINE: validate existence before update — throws KeyNotFoundException if not found
        public async Task<FrequencyDto> UpdateAsync(FrequencyDto dto)
        {
            if (dto is null) throw new ArgumentNullException(nameof(dto));

            bool exists = await _repository.ExistsAsync(dto.Frequencyid);
            if (!exists)
                throw new KeyNotFoundException($"Frequency with frequencyid {dto.Frequencyid} was not found.");

            Frequency entity = _mapper.Map<Frequency>(dto);
            Frequency updated = await _repository.UpdateAsync(entity);
            return _mapper.Map<FrequencyDto>(updated);
        }

        // TRANSFORMENGINE: throws KeyNotFoundException if not found before delete
        public async Task DeleteAsync(int frequencyid)
        {
            bool exists = await _repository.ExistsAsync(frequencyid);
            if (!exists)
                throw new KeyNotFoundException($"Frequency with frequencyid {frequencyid} was not found.");

            await _repository.DeleteAsync(frequencyid);
        }

        public async Task<bool> ExistsAsync(int frequencyid)
        {
            return await _repository.ExistsAsync(frequencyid);
        }
    }
}
