/*
 * TRANSFORMENGINE MIGRATION — ReviewItemService.cs
 * Pattern  : stack-upgrade/msaccess-frm-to-dotnet10-mvc-e2e  Phase 3 — Application Layer - DTOs + Service Interfaces + EntityMapper + Services (Steps 4-6)
 * Migrated : 2026-07-06
 *
 * CHANGED:
 *   - New Application service implementing IReviewItemService for ReviewItem CRUD (Other Tab review items lookup, frmMaintainance)
 *   - Single integer PK (itemid) — GENERATED BY DEFAULT AS IDENTITY
 *   - Delegates all persistence to IReviewItemRepository; no direct DbContext usage
 *   - All methods are async end-to-end
 *   - Throws ArgumentException on null/invalid input; KeyNotFoundException when entity not found
 *   - AutoMapper used for all entity <-> DTO conversions
 *
 * PRESERVED:
 *   - All business guards: null-input validation, not-found checks before update/delete
 *
 * DEFERRED / REQUIRES HUMAN REVIEW:
 *   - none — fully automated.
 */

using Apha.PIMS.Application.Dtos;
using Apha.PIMS.Application.Interfaces;
using Apha.PIMS.Core.Entities;
using Apha.PIMS.Core.Interfaces;
using AutoMapper;

namespace Apha.PIMS.Application.Services
{
    // TRANSFORMENGINE: service orchestrates IReviewItemRepository; single integer PK (itemid); lookup/reference table
    public class ReviewItemService : IReviewItemService
    {
        private readonly IReviewItemRepository _repository;
        private readonly IMapper _mapper;

        public ReviewItemService(IReviewItemRepository repository, IMapper mapper)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        // TRANSFORMENGINE: returns full list for review-item dropdown / lookup usage
        public async Task<List<ReviewItemDto>> GetAllAsync()
        {
            List<ReviewItem> entities = await _repository.GetAllAsync();
            return _mapper.Map<List<ReviewItemDto>>(entities);
        }

        // TRANSFORMENGINE: returns nullable — controller maps null to 404; single integer PK lookup
        public async Task<ReviewItemDto?> GetByIdAsync(int itemid)
        {
            ReviewItem? entity = await _repository.GetByIdAsync(itemid);
            return entity is null ? null : _mapper.Map<ReviewItemDto>(entity);
        }

        // TRANSFORMENGINE: validate non-null DTO before first await
        public async Task<ReviewItemDto> CreateAsync(ReviewItemDto dto)
        {
            if (dto is null) throw new ArgumentNullException(nameof(dto));

            ReviewItem entity = _mapper.Map<ReviewItem>(dto);
            ReviewItem created = await _repository.AddAsync(entity);
            return _mapper.Map<ReviewItemDto>(created);
        }

        // TRANSFORMENGINE: validate existence before update — throws KeyNotFoundException if not found
        public async Task<ReviewItemDto> UpdateAsync(ReviewItemDto dto)
        {
            if (dto is null) throw new ArgumentNullException(nameof(dto));

            bool exists = await _repository.ExistsAsync(dto.Itemid);
            if (!exists)
                throw new KeyNotFoundException($"ReviewItem with itemid {dto.Itemid} was not found.");

            ReviewItem entity = _mapper.Map<ReviewItem>(dto);
            ReviewItem updated = await _repository.UpdateAsync(entity);
            return _mapper.Map<ReviewItemDto>(updated);
        }

        // TRANSFORMENGINE: throws KeyNotFoundException if not found before delete
        public async Task DeleteAsync(int itemid)
        {
            bool exists = await _repository.ExistsAsync(itemid);
            if (!exists)
                throw new KeyNotFoundException($"ReviewItem with itemid {itemid} was not found.");

            await _repository.DeleteAsync(itemid);
        }

        public async Task<bool> ExistsAsync(int itemid)
        {
            return await _repository.ExistsAsync(itemid);
        }
    }
}
